### ISSUE TITLE
TreeListCtrl migration to Phoenix?

### ISSUE THREAD

**Issue by ibell** [wxWidgets/Phoenix#1041]
I see that TreeListCtrl has been moved from wx.gizmos to wx.dataview.  The API seems to have changed as well, in trivial and non-trivial ways.  The following functions have been removed, and I can't see a clear mapping to the new class:

```
DeleteRoot
AddRoot
```

Or should I switch over to ``wx.lib.agw.customtreectrl.CustomTreeCtrl``?  That seems to retain more of the old API than ``wx.dataview.TreeListCtrl``

**Comment by mesalu** [comment]
does `wx.lib.gizmos.treelistctrl` match what you're looking for?

**Comment by RobinD42** [comment]
Despite having the same class name, `wx.dataview.TreeListCtrl` is a very different class, with different API design and intended use cases.

The `wx.gizmos` package was not ported to Phoenix until recently, because it needed to be ported from C++ and wrappers to pure Python, due to the original C++ code being unsupported for a long time. So that is why people tend to find the `wx.dataview` version of the class first.

`wx.lib.gizmos.treelistctrl` is mostly API compatible with the old `TreeListCtrl` class, but it's really just a thin layer over the `wx.lib.agw.hypertreelist.HyperTreeList` class with tweaks to help with the API compatibility. The `HyperTreeList` class is actually more capable and flexible so you may want to just port your code to use it directly.

https://docs.wxpython.org/wx.lib.gizmos.treelistctrl.TreeListCtrl.html
https://docs.wxpython.org/wx.lib.agw.hypertreelist.HyperTreeList.html
