### ISSUE TITLE
DLL load failed while started the app

### ISSUE THREAD

**Issue by jekoie** [wxWidgets/Phoenix#1114]
hi, i use python2.7 and wxpython v4.0.0a1 build a app and install it at windows xp , i packeged it use cx_freeeze module, it run well in some windows xp system, but sometime it run DLL load errrors?
can anyone help me?
![img_1810](https://user-images.githubusercontent.com/6836400/50389400-d0a35580-0764-11e9-8475-308ce23d994e.JPG)

**Comment by swt2c** [comment]
Can you translate that message to English?

**Comment by RobinD42** [comment]
It is likely that cx_freeze is not finding all of the DLLs that wxPython needs or load at runtime, or perhaps the DLLs that those DLLs need. So, in other words, it is may not be including the DLLs for wxWidgets, or the MSVC runtime library DLLs, or perhaps some system level DLLs that are missing on the target system due to it not being updated fully.  

You can use a tool called Dependency Walker (google it) to track down what DLLs are trying to be loaded but not found. (Warning: a lot of the low-level it says are missing are not really needed in our case because they are dynamically loaded only in special circumstances.)

**Comment by infinity77** [comment]
@swt2c it doesn’t look this has anything to do with wxPython
