### ISSUE TITLE
Button does not take up full space allocated to it on Mac OS X

### ISSUE THREAD

**Issue by programmingkidx** [wxWidgets/Phoenix#1121]
**Operating system**: Mac OS 10.12.6
**wxPython version & source**: '4.0.3 osx-cocoa (phoenix) wxWidgets 3.0.5'
**Python version & source**: 3.7.2

**Description of the problem**:
The button in this program is suppose to take up all the space in the frame, but only takes up the full horizontal space. The vertical space is not fully take up. When a second line of text is included in the label, the button takes up the full space like it is suppose to. 

```
# Does not take up the full space
from wx import *
app = App()
frame = Frame(None, ID_ANY, "Main window")
b1 = Button(frame, ID_ANY, "Button")
frame.Show()
app.MainLoop()

```
```
# Does take up the full space
from wx import *
app = App()
frame = Frame(None, ID_ANY, "Main window")
b1 = Button(frame, ID_ANY, "Button\n") # second line of text in the label
frame.Show()
app.MainLoop()
```

**Comment by RobinD42** [comment]
This is due to the nature of the native button widget. As far as wxWidgets is concerned the widget does take the full client size of the frame, but macOS only draws the portion that fits in the standard button height. There isn't anything we can do about that, but as you've found it's not too hard to trigger the use of a different kind of button widget. There are also the generic button widgets in the `wx.lib.buttons` module.
