### ISSUE TITLE
BusyCursor in ListCtrl not working

### ISSUE THREAD

**Issue by Leon-001** [wxWidgets/Phoenix#1161]
Hi!

**Operating system**:
Kubuntu. Uname gives:
4.15.0-45-generic #48-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

**wxPython version & source**: 
'3.0.2.0 gtk3 (classic)'
and
'4.0.4 gtk3 (phoenix) wxWidgets 3.0.5'

**Python version & source**:    
Python 2.7.15rc1 (distro version)
and
Python 3.6.7 (distro version)

**Description of the problem**:
I have a ListCtrl. When I use the context menu (right mouse button) in order to start an action, I would like to use wx.BeginBusyCursor() in order to signal the user she has to wait.

But the mouse cursor does not change, when I start the action.

I have attached a sample script: [App_test_listctrl_busyCursor.txt](https://github.com/wxWidgets/Phoenix/files/2841059/App_test_listctrl_busyCursor.txt)

On my system (Kubuntu) it runs with python2 and python3.
In both cases the mouse does not change.

When I start the same command by clicking a button, it works as expected: the mouse cursor shows the busy-symbol.

**Comment by RobinD42** [comment]
Some things on wxGTK can not happen as immediately as they can on the other platforms. Instead they require a round trip(s) between the client application and the X server. Due the the asynchronous nature of X that means that there needs to be some iterations of the event loop for the operation to be completed. 

So in your example those pending events can't happen until after you've already ended the busy cursor, because your OnDetails handler is blocking the return to the event loop.  The workaround is simple, just give the event loop a chance to run after you've changed the cursor, and before you start your time-consuming thing. One easy way (but perhaps unsafe depending on what your long-running task does) is to call the app's Yield method.

```python
    def OnDetails(self, event):
        wx.BeginBusyCursor()
        wx.GetApp().Yield()    # add this line
        print('started')
        time.sleep(2)
        print('finished')
        wx.EndBusyCursor()
        event.Skip()
```

See https://wiki.wxpython.org/LongRunningTasks for more info and some other options.
