### ISSUE TITLE
TreeList not firing selection events

### ISSUE THREAD

**Issue by CrawfordW** [wxWidgets/Phoenix#1164]
TreeList is not firing a wx.EVT_TREE_SEL_CHANGED event when an item is selected.
I've tried both wx.lib.agw.hypertreelist, and wx.gizmos.TreeListCtrl.
wx.EVT_TREE_ITEM_ACTIVATED events are working correctly.

Running Windows 10 with 
Python version 3.7.1
wxPython version 4.0.4

Following is a minimal bit of code that will show the problem, and also allow comparison with the basic TreeCtrl widget...

```python
import wx
import wx.gizmos

class TestFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, title="TreeListCtrl", size=(400, 500))

        self.tree = wx.gizmos.TreeListCtrl(self, style= wx.TR_DEFAULT_STYLE | wx.TR_FULL_ROW_HIGHLIGHT)
        self.tree.AddColumn("Column 1")
        self.tree.SetMainColumn(0)
        self.tree.SetColumnWidth(0, 200)

        # Replace the above 4 lines with this, to see how it should work...
        # self.tree = wx.TreeCtrl(self, style= wx.TR_DEFAULT_STYLE | wx.TR_FULL_ROW_HIGHLIGHT)

        root = self.tree.AddRoot("Test")

        for cat in range(0, 10):
            new_cat = self.tree.AppendItem(root, "Category " + str(cat))
            for item in range(0, 5):
                new_item = self.tree.AppendItem(new_cat, "Item " + str(item))

        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.onSelectionChanged, self.tree)
        self.Bind(wx.EVT_TREE_ITEM_ACTIVATED, self.onDblClick, self.tree)

        self.tree.Expand(root)

    def onSelectionChanged(self, event):
        item = event.GetItem()
        print(self.tree.GetItemText(item) + " Selected")

    def onDblClick(self, event):
        item = event.GetItem()
        print(self.tree.GetItemText(item) + " Double-click")

if __name__ == "__main__":
    app = wx.App()
    frame = TestFrame()
    frame.Show()
    app.MainLoop()
```

**Comment by RobinD42** [comment]
The problem you've run into is due to the `TreeListCtrl` being a composite of multiple widgets. The `EVT_TREE_SEL_CHANGED` is actually coming from one of the sub-widgets, but you are binding the event handler for events coming from the parent of that sub-widget:

```python
self.Bind(wx.EVT_TREE_SEL_CHANGED, self.onSelectionChanged, self.tree)
```

So the event is being sent, but your binding is not catching it because it's looking for events with a different ID.

If you drop the `self.tree` parameter from that line, then the binding will match events of that type from any source widget within `self`. If you need to have multiple `TreeListCtrls` in the same frame for some reason then you can use the sub-widget as the source, like this:

```python
self.Bind(wx.EVT_TREE_SEL_CHANGED, self.onSelectionChanged, self.tree.GetMainWindow())
```

Or just bind directly to the tree, like this:

```python
self.tree.Bind(wx.EVT_TREE_SEL_CHANGED, self.onSelectionChanged)
```

**Comment by CrawfordW** [comment]
Thanks for your help, Robin.
