### ISSUE TITLE
lack of wheel package for *nix os on PyPi

### ISSUE THREAD

**Issue by leileigong** [wxWidgets/Phoenix#1195]
When does wheel package for linux will be uploaded  to pypi?
thanks.

**Comment by RobinD42** [comment]
We can't build generic packages for any Linux because the "manylinux1" spec does not include enough, or new enough, packages that are required for wxWidgets to build. There are however some wheels built for a few specific linux distros. Details can be found on the download page: https://wxpython.org/pages/downloads. And there are details about building your own wheels for your distro of Linux here: https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip.
