### ISSUE TITLE
Adding/Removing controls during runtime to/from ScrolledWindow

### ISSUE THREAD

**Issue by COM8** [wxWidgets/Phoenix#1221]
**Operating system**: Windows 10
**wxPython version & source**: 4.0.4 & PIP
**Python version & source**: 3.7.2 & Python installer

**Description of the problem**:

I'm trying to add/remove multiple items to a [ScrolledWindow](https://wxpython.org/Phoenix/docs/html/wx.ScrolledWindow.html).  
At the moment I have the following control architecture:
![Imgur](https://i.imgur.com/JV0JF6v.png)

I want to add multiple instances of the `resultItem_panel` to the `result_scrolledWindow`.  
When I do so I first have to scale the window manually by dragging it with the cursor for it to update and the `result_scrolledWindow` to show the scroll bars.  
My code at the moment:

```python
def __addPublication(self, pub: Publication) -> None:
    resultItem_panel = ResultItemPanel(self, pub)

    # Add to parent sizer:
    self.result_sizer.Add(resultItem_panel, 0, wx.ALL, 5)
    self.Layout()
    self.Parent.Fit()

    # Store it so we later can Destroy() it again:
    self.resultItemPanels.append(resultItem_panel)

def clearPublications(self) -> None:
    for pub in self.resultItemPanels:
        pub.Destroy()
    self.resultItemPanels = []

    self.Layout()
    self.Parent.Fit()
```

What am I doing wrong here?

[Stackoverflow Question](https://stackoverflow.com/posts/55905491/edit)

**Comment by RobinD42** [comment]
What isn't working?

**Comment by COM8** [comment]
![ss](https://user-images.githubusercontent.com/11741404/57757302-7300ad00-76f5-11e9-9e23-470b9be5ecdb.gif)

Once the progress bar finishes I add a bunch of `ResultItemPanel` widgets to the `result_scrolledWindow`.
This breaks the layout and I have to rescale the window first (like seen in the gif) for the layout to update properly.

**Comment by RobinD42** [comment]
Using `Layout` should help with that, but perhaps you are not calling the correct one. When there are nested windows and/or sizers involved calling one for further up the hierarchy may not result in the Layout going fully recursive, if there is something along the way that does not need to have it's size changed. Without a EVT_SIZE event for the mid-level item there will be no automatic call to its Layout.

Try calling Layout on the parent of the widgets that were removed (assuming that parent also has the sizer they were in.) If that doesn't do it then try the next one up the hierarchy. If that doesn't help then use the [WIT](https://wiki.wxpython.org/Widget%20Inspection%20Tool) to interactively play with the widgets/sizers and figure out what it will take to adjust your layout like you want.

Also, I'd get rid of the calls to `Fit`. It's handy at the top level when the top-level window is first created, but it tends to get in the way otherwise.

**Comment by COM8** [comment]
I wasn't able to get it working with just calling `Layout()`.
That's what did the trick for me:
```python
self.result_sizer.Layout()
self.PostSizeEvent()
```

Thanks for your help!

**Comment by Metallicow** [comment]
@COM8 Yes sometimes Layout() itself doesn't always work just by itself. Not sure if it is Windows specific... This also applies to Update also sometimes. Normally if you have to resize the size gripper, take a hint that either SendSizeEvent() or PostSizeEvent() should follow at the end somewhere. Usually I put a PostSizeEvent to the main frame after initialization of all the startup stuff and after GUI updates that hide or show widgets.
