### ISSUE TITLE
CustomTreeCtrl edit label remains stuck forever sometimes

### ISSUE THREAD

**Issue by Nyral** [wxWidgets/Phoenix#1235]
Windows 10 (or Windows 7)
wxPython 4.0.6 (pip)
Python 3.7.3 [32bit]

From what I can tell, it seems that I'm able to somehow select the label from behind the TextCtrl and trigger a second edit label instance that can't be closed.
Or maybe KillFocus doesn't trigger correctly? I dunno.

Here's me reproducing it with the example from wxDemo:
![2019-05-28_01-42-14](https://user-images.githubusercontent.com/39315668/58441539-6dd73100-80eb-11e9-8b9f-cac02acf219f.gif)

Another example (from another GUI):
![2019-05-19_20-20-38](https://user-images.githubusercontent.com/39315668/58441731-f73b3300-80ec-11e9-9d85-de07908e5018.gif)

**Comment by cbeytas** [comment]
When you left-click on a label, a TreeEditTimer is started. After ```_DELAY``` (500ms) the tree will edit the label.

If you are already editing the label this shouldn't happen, but the TreeTextCtrl doesn't fully cover the label area. So if you click just outside the TreeTextCtrl, the ```TREE_HITTEST_ONITEMLABEL``` test will pass and the timer will be started. After 500ms a second TreeTextCtrl is spawned on top of the old one.

When you change the selection, only the most recent TreeTextCtrl is Destroyed and the old one is left orphaned in the tree.

Could be fixed in ```customtreectrl.py``` at the end of the Edit() method:
```
        if self._editCtrl != None and item != self._editCtrl.item():
            self._editCtrl.StopEditing()

        self._editCtrl = TreeTextCtrl(self, item=item)
        self._editCtrl.SetFocus()
```
if ```self._editCtrl``` is not None, an edit control already exists in the tree.
I believe it should not assign ```self._editCtrl``` to a new TreeTextCtrl without guaranteeing the previous one is destroyed.

**Comment by Nyral** [comment]
@cbeytas Thank you for looking into this! It means a lot to me.

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/wxpython-4-1-0-released/34564/1
