### ISSUE TITLE
MDIParentFrame is closed when opening MDIChildFrame on macOS

### ISSUE THREAD

**Issue by pdelporte** [wxWidgets/Phoenix#1315]
**Operating system**: macOS Mojave 10.14.5
**wxPython version & source**:   4.06, installed with pip       
**Python version & source**:  3.6.5          

**Description of the problem**:
When you create the first MDIChildFrame, the ParentMDIChildFrame is close (hidden ?), and the menu "Window" does not appears. The MDIChildFrame are just sort of independent windows. The same code works well on Windows.

```python
import wx


class MDIFrame(wx.MDIParentFrame):
    def __init__(self):
        wx.MDIParentFrame.__init__(self, None, -1, "MDI Parent", size=(600, 400))
        menu = wx.Menu()
        menu.Append(5000, "&New Window")
        menu.Append(5001, "&Exit")
        menubar = wx.MenuBar()
        menubar.Append(menu, "&File")

        self.SetMenuBar(menubar)
        self.Bind(wx.EVT_MENU, self.OnNewWindow, id=5000)
        self.Bind(wx.EVT_MENU, self.OnExit, id=5001)

    def OnExit(self, evt):
        self.Close(True)

    def OnNewWindow(self, evt):
        win = wx.MDIChildFrame(self, -1, "Child Window")
        win.Show(True)


app = wx.App()
frame = MDIFrame()
frame.Show()
app.MainLoop()

```

**Comment by RobinD42** [comment]
This is intentional, although the missing Window menu is a bug which has been fixed in 4.1 already. 

The equivalent of MDI on OSX is multiple SDI windows in the same process. The best way to make it conform to the Mac standards is to just use the parent frame for its menubar and perhaps a `TaskBarIcon` menu, but never show it. The user will be able to interact with the menus to create new windows or open files or whatever.
