### ISSUE TITLE
helloworld2.py has 2 errors

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [wxWidgets/Phoenix#1318]
https://wxpython.org/pages/overview/#hello-world

This web-page and source helloworld2.py has 2 errors:

1.
incorrect shebang
#!/bin/python
(with this shebang helloworld2.py not work on my Windows)

should be as
#!/usr/bin/env python3
or
#!/usr/bin/python3

2.
st = wx.StaticText(pnl, label="Hello World!", pos=(25,25))
this work fine on Windows, but not work on Linux Mint(not resize StaticText component for big label)

Should be as
st = wx.StaticText(pnl, label="Hello World!", pos=(25,25), size=(0,0))
this work fine on both systems.

**Comment by RobinD42** [comment]
> https://wxpython.org/pages/overview/#hello-world
> 
> This web-page and source helloworld2.py has 2 errors: 
> 
> incorrect shebang

This varies by platform, and how Python is installed, and if a virtualenv is being used, and... whatever.


> st = wx.StaticText(pnl, label="Hello World!", pos=(25,25))
> this work fine on Windows, but not work on Linux Mint(not resize StaticText component for big label)

It is resizing it to the new best size, but since it's on X11 and the event loop isn't running yet I guess it isn't able to get a correct best size yet.  So using a sizer is even better since it will redo the resize on the next size event.
