### ISSUE TITLE
The repository located at wxpython.org is not a trusted or secure host and is ...

### ISSUE THREAD

**Issue by WDBell** [wxWidgets/Phoenix#134]
Imagine that!

I had entered,
pip install -U --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

Installation apparently successful when I declared the domain 'trusted-host'.

**Comment by Ryex** [comment]
I do not believe this is something that can be fixed on the project's end. pip and the python community as a whole decide what a trusted host by default. 
It's possible to configure this locally via pip config file by defining wxpython.org as a trusted host there https://pip.pypa.io/en/stable/user_guide/#config-file

That said, once the project is posted to pypi it won't be a problem because you'll be able to 
`pip install wxpython-phoenix` and it will just work. My understanding is this should happen 'soon' as there has been a large push and huge uptick in activity here of late.

**Comment by WDBell** [comment]
Thanks very much for responding.

**Comment by RobinD42** [comment]
wxpython.org recently was secured with an SSL certificate, so you can access the snapshots site with `https://...` now, using the command shown in the `README.txt`.  That should make pip happy.
