### ISSUE TITLE
Bug in wx.Frame.SetShape

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/Phoenix#1478]
```
wxPython 4.0.7.post1 msw (phoenix) wxWidgets 3.0.5
Python 3.7.5 Stackless 3.7 (tags/v3.7.5-slp:f7925f2a02, Oct 20 2019, 15:28:53) [MSC v.1916 64 bit (AMD64)]
Windows 7 x64 Service Pack 1 ( 6.1.7601 )
```

when I used the image below

setting the shape of a shaped frame. using this code

```python
r = wx.Region(bmp)
self.hasShape = self.SetShape(r)
```

the returned value from the call to SetShape is True. and the resulting shaped frame is a gray box with the blue pixels.. While I  know this should fail in producing a properly shaped frame It should not be returning True..

![image](https://user-images.githubusercontent.com/10932297/71925221-ceccea00-314d-11ea-997d-38b1237842f7.png)

Now adding another bit of strange behavior.
Then when I use the image below which should work to create the shaped frame I get the exact same results a gray box with a blue circle. I expected a gray circle with a blue outline.

![image](https://user-images.githubusercontent.com/10932297/71925494-6a5e5a80-314e-11ea-9a3f-042ee30416ad.png)

In both cases the blue pixels have an alpha value of 255 and all of the rest of the pixels have an alpha value of 0.

I am not entirely sure why the images are appearing as black with a blue circle. Something odd going on with the alpha channel of the pixel data. The images were created using wx.Image. I loaded a PNG and extracted the pixels I wanted from the loaded png and created a new wx.Image instance. added the pixels I set the blue pixels to have an alpha level of 255 and all other to be 0. I know that the default color of a wx.Image is (0, 0, 0, 255). I then saved the image as a png

It displays properly in Windows and also in Paint.NET. just not when pasted into Github.. Odd.....

**Comment by RobinD42** [comment]
The `wx.Region(bmp)` constructor uses the bitmap's mask to determine which pixels are transparent and which are not. The docs say this about it: "The bitmap’s mask is used to determine transparency. If the bitmap doesn’t have a mask, the bitmap’s full dimensions are used." (Follow the link to more details in the doc for `wx.Region.Union`)

An alpha channel is not the same as a mask, even if all the alpha values are either 0 or 255. You can check if there is a mask with `bmp.GetMask() is not None`. There are various ways to add a mask to a bitmap, I'd try loading the file into a `wx.Image`, calling it's `ConvertAlphaToMask` method, and then `ConvertToBitmap`. Other possibilities are:

* Edit the image in some other tool to give it a mask rather than an alpha channel, then you don't need to do anything extra with it at runtime.
* You can create a `wx.Mask` and pass it to `bmp.SetMask`
* The `bmp.SetMaskColour` method is handy if the pixels to be masked out are a solid color.

**Comment by RobinD42** [comment]
Oh, and the true value returned from `SetShape` is correct, since it was able to do what you asked it to do: set the shape to the region it was given (the full image size).

**Comment by kdschlosser** [comment]
and I see what happened.... in the docs for wx.Region these 2 constructors are one on top of each other. 

```
__init__ (self, bmp)

Constructs a region using a bitmap.

See Union for more details.

Parameters
    bmp (wx.Bitmap) –


__init__ (self, bmp, transColour, tolerance=0)
Constructs a region using the non-transparent pixels of a bitmap.
```

I must of in my head used the description from the one with the constructor of the other..

OK so when passing a bitmap shouldn't it create a back off a boolean response to an alpha channel?
alpha > 0

Otherwise I do not see how a mask could be created without having prior knowledge of what the bitmap is. how would one go about creating a region to pass to SetShape where it treats all alpha values of 0 as transparent..

**Comment by kdschlosser** [comment]
i got it sorted.. I have never used a mask so this is a learning thing for me.
