### ISSUE TITLE
Simple app called multiple times from ipython causes crash [macOS]

### ISSUE THREAD

**Issue by in-tension** [wxWidgets/Phoenix#1490]
When I run a simple app multiple times from ipython, it causes a crash.

![image](https://user-images.githubusercontent.com/20464764/72762940-7b2bb900-3baf-11ea-8739-4d2b9e95080e.png)

This has happened with both helloworld examples [here](https://wxpython.org/pages/overview/#hello-world), both the basic helloworld and helloworld2.py.

for your convience, the basic helloworld code:

```
import wx
app = wx.App()
frm = wx.Frame(None, title="Hello World")
frm.Show()
app.MainLoop()
```

# In Detail
I run the file from ipython using `%run helloworld.py`
A window pops up, I close it using the x icon
Then I run it again from the same ipython instance

On the third time, when I close the window, ipython crashes and says:

```
objc[56326]: autorelease pool page 0x7fe86e09b000 corrupted
  magic     0x0d1f2370 0x00000001 0x0d11b440 0x00000001
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x10d1efab0
  should be 0x7fffc5aa23c0

Abort trap: 6
```

I've done this several times, and every time it does this.
except one time it gave me a `Segmentation fault: 11`.
When I alternate which file I run, it crashes on the fourth try, even if I only ran each individual file twice (versus 1 file once and 1 file three times).

**os**: macOS 1.12/Sierra (which is a little old, 2015 I think)
**wxPython**: from pypi, versions 4.06 and 4.07
**Python**: homebrew, 3.7.4, calling from ipython

**Comment by RobinD42** [comment]
The multiple `%run` commands run the files within the same kernel process, but wxWidgets makes assumptions about there only ever being 1 `wx.App` in any 1 process. So what you are seeing is likely due to the multiple app objects stepping on each other's toes.

You can get around this problem by restarting the IPython kernel between runs of wx applications. Or you run the wx applications outside of IPython. Using the `%gui wx` command may also be an option, but I think it needed an update to work with wxPython4, and I'm not sure if  those changes have been released yet.
