### ISSUE TITLE
Question about code completion and real classes behind

### ISSUE THREAD

**Issue by martinlombana** [wxWidgets/Phoenix#1528]
**Operating system**:
Windows 10 / Pycharm Pro
**wxPython==4.1.0a1.dev4539+c51cdd23**
**Python 3.7.3**

This is not a bug per sé. I am wondering why, when I try to inspect with pycharm the wx classes that I use, i just get   # real signature unknown; restored from __doc__:

```
    def SetUnderlined(self, underlined): # real signature unknown; restored from __doc__
        """
        SetUnderlined(underlined)
        
        Sets underlining.
        """
        pass

```

And I can not really know, without going to the online docs, what params are expected or possible for a given class or function. I have looked for the real classes, but I can't find them. 

Is there any way to use or to get the code as is, with all those signatures, so I can have code completion and also do introspection on the functions and classes?

Thanks.

**Comment by Metallicow** [comment]
try uploading your image again. it sorta failed...

**Comment by Metallicow** [comment]
try something like this on your OS
`C:\Python27\Lib\site-packages\wx-4.1.x-msw\wx\core.pyi`

**Comment by martinlombana** [comment]
I am using Python 3, and a virtualEnv. But I can't find the core.pyi. But I can compile my app without issues. And I am using the correct version of wx41. I installed with a wheel from the distros page.

**Comment by martinlombana** [comment]
Here:
D:\Sync\Martin\inProgress\_virtualenvs\wx41\Lib\site-packages\wxPython-4.1.0a1.dev4539+c51cdd23.dist-info

I can only find this: 
entry_points.txt  INSTALLER  LICENSE.txt  METADATA  RECORD  top_level.txt  WHEEL

**Comment by Metallicow** [comment]
IIRC it should be included in the .whl file so where ever it gets installed should be the location or just extract it from the whl. a whl file is basically a zip.

**Comment by Metallicow** [comment]
`wxPython-4.1.0a1.dev4539+c51cdd23.dist-info` this dir in the whl is just for pip or other package managers. It is basically just meta stuff. Look in the `wx` directory for the .pyi files

**Comment by martinlombana** [comment]
Thanks!

I found **core.pyi** in **Lib\site-packages\wx.**

1. How can I set pycharm to look for the classes there?

**Comment by Metallicow** [comment]
idunno. dont use it.

**Comment by Metallicow** [comment]
read the header in the pyi file. it is generated, but has some basic infos.

**Comment by RobinD42** [comment]
The "real classes" are in compiled C++ code and PyCharm and other introspection tools are only able to get a minimal bit of metadata from there, so that is why it falls back to the docstring. Alongside the extension modules (`*.pyd`) and the supporting `*.py` files, the build also generates a set of `*.pyi` files that contain stubs of all the classes that are in the compiled extension modules. PyCharm (and other IDEs) should automatically recognize and use the stub files to provide more information which it can't get from scanning the compiled extensions. (My guess is that's probably where it is getting what you are already seeing.) The info in the stubs could be made better by including type hinting and such, but that hasn't happened yet.

I haven't actively used PyCharm for a while, but I seem to recall that it has the ability to be taught how to load documentation pages for the item currently under the cursor, as long as the docs use URLs that can be built from class name, method name, etc.
