### ISSUE TITLE
frame style options CAPTION and NO_BORDER change panel sizing behavior

### ISSUE THREAD

**Issue by tscizzlebg** [wxWidgets/Phoenix#1537]
**Operating system**: Windows 10
**wxPython version & source**: wxPython==4.0.7.post2 from pypi
**Python version & source**: Python 3.7.6 from Miniconda

**Description of the problem**:

When using frame style of `DEFAULT_FRAME_STYLE` by default the panel starts out filling the frame. When removing the `CAPTION` style or adding the `NO_BORDER` style, the panel starts out taking up only a tiny corner of the frame.

```python
import wx

class ExampleApp(wx.App):
    def OnInit(self):
        frameStyle = wx.DEFAULT_FRAME_STYLE ^ wx.CAPTION
        mainFrame = wx.Frame(
            parent=None,
            id=wx.ID_ANY,
            title="Example for GitHub",
            pos=(100, 100),
            size=(300, 100),
            style=frameStyle,
        )
        wx.Panel(mainFrame)
        mainFrame.Show()

        return True

app = ExampleApp(False)
app.MainLoop()
```

**Comment by RobinD42** [comment]
Yep, this is known behavior, and it's been this way forever. Basically it stems from there not being an initial `EVT_SIZE` event due to the size already being set and, in this case, that the border style being one that doesn't cause an adjustment to the size after the frame is shown. The easiest workaround is to just call the frame's `SendSizeEvent()` method after the frame's content and sizers if any have been added. That will trigger the running of the frame's auto-layout code.

**Comment by tscizzlebg** [comment]
Ok, makes enough sense, so only suggestion would be to document this behavior somewhere (I suggest next to the CAPTION or NO_BORDER style docs).

Since it is surprising behavior, to attempt to remove the border by adding that 1 style, and have that shrink the app to a tiny square.
