### ISSUE TITLE
wxPython 4.1.0/wx.Locale.FindLanguageInfo: LocaleName returns the same string as CanonicalName

### ISSUE THREAD

**Issue by josephsl** [wxWidgets/Phoenix#1592]
**Operating system**: Windows 10
**wxPython version & source**: 4.1.0 dev+4692, snapshots wheel
**Python version & source**: 3.7.7, 3.8.2 official 32-bit builds

**Description of the problem**:
Possibly related to #1440: after importing wx from Python interpreter, try:

print(wx.Locale().FindLanguageInfo("en").LocaleName)

And:

print(wx.Locale().FindLanguageInfo("en").CanonicalName)

Expected: "English_United Kingdom.1252"
Actual: "en-GB"

In short, LocaleName returns same locale string as CanonicalName. This causes Python's locale module to complain that locale name set by wxPython ("en-GB") cannot be parsed. Translations are not affected, but affects other parts of the app that will require character encoding considerations such as text processing.

For practical example:

1. Clone NVDA screen reader source code (https://github.com/nvaccess/nvda)
2. After cloning submodules, replace wxPython 4.0.3 found in include/wxPython folder with the version noted above.
3. Compile NVDA from source and run it (scons source; py -3.7-32 drive/path/to/nvda/source/nvda.pyw).
4. Try navigating with a web browser such as Microsoft Edge 81 - you should hear beep sounds.
5. Press Insert+F1 to display NVDA log viewer and inspect the last traceback where locale.getlocale shows ValueError.

Practical implications: without resolving this, it becomes harder for multilingual applications or text processors that uses wxPython (such as screen readers) to migrate to wxPython 4.1.0 and future Python releases.

Thanks.

**Comment by kdschlosser** [comment]
I attached a script I wrote that is a wrapper/monkey patch for wx.Locale to fix the problems it has with Windows. You can run the file and it will spit out every single locale that is installed on the computer as a test if you like to see that it runs. I have not yet tried it in a full blown application But I thought I would offer it to see if it helps solve the issue you are having.

The basic use of it is this. You would import it at the beginning of your application. before wx gets imported anywhere. and that's it.

I extended it so that it will accept iso codes in the constructor you have to use 
the keyword iso_code

```python
import wx_locale
import wx

locale = wx.Locale(iso_code='en_US')
``` 

It should work on all python versions that wxPython supports.
wxWidgets uses LCID's for identifying locales which is what is causing the problems. Windows has "virtual" LCID's and locales can have the same LCID. so the OS gets all kinds of confused when you ask for something using an LCID that is virtual. That script I have corrected the issue and query the Windows API using the ISO code instead.

Python has it's own unique set of issues when dealing with locals. and I have worked through them as well. So when you create a wx.Locale instance it will set the pyhton locale as well as the c\c++ locale correctly. 

I also added into it the ability to get the language name and country name in the languages native script and also the ability to get the language name and country name in the localized script and the same for english as well. So if you wanted to provide a language selection dialog that would show the name of a country and language in that languages script you would be able to. I do not know how important a feature like that would be for NVDA because of the nature of the software but it may be..

Give it a shot and see if it corrects your problems.. Remember the trick to using the new functionality is to specify the language by ISO-639 codes and using the keyword "iso_codes" in the constructor

[wx_locale.zip](https://github.com/wxWidgets/Phoenix/files/4534870/wx_locale.zip)

**Comment by josephsl** [comment]
Hi, will report back after testing this. CC @LeonardDer, @feerrenrut in case they wish to comment.

**Comment by kdschlosser** [comment]
OK i just fixed an issue with the script that would cause an appcrash if you used

```python
print(wx.Locale().FindLanguageInfo("en").LocaleName)
print(wx.Locale().FindLanguageInfo("en").CanonicalName)
```
There is an issue with wx.Locale and it always returning the "system" locale. On windows this is actually incorrect. We want to have it returnthe currenmt thread UI locale. This has been fixed.

on my system if I used wx.Locale() with no arguments it would always return the locale for English in Great Brittan. and not the actually set locale. This has been repaired.

a wx.LanguageInfo instance should be just that. the language information and nothing more. because the same language can be used in conjunction with multiple countries thus making a different locale a language should not return a canonical name that has anything to do with a country.

a language returning a locale iso code by using CanonicalName was not correct. 
lang.CanonicalName
"en_US" 

This has been fixed and is now going to return "en"

lang.LocaleName is now going to return "en_US" as it should. it will add together the canonical name of the language to the canonical name of the currently set locals country to create the en_US.

If you want what I call the ansi name, which is the description of the language added to the description of a country and the ansi code page you need to call a method to achieve this.

```python
import wx_locale
import wx

locale = wx.Locale()
language = locale..FindLanguageInfo("en")
print(language.GetANSIName(locale))
```

this outputs "English_United States.windows-1252"
and here is a one liner that will achieve the same thing.

```python
print(wx.Locale.FindLanguageInfo("en").GetANSIName(wx.Locale()))
```

There are a series of pitfalls and problems when dealing with the windows locale settings coupled to wxPython and Python in general. it all depends on what python version you are running along with what wxPython version you are running as well. It make a pretty large mess.

depending on your python version you would need to pass any one of the following to be able to set the locale in python

English_United States.windows-1252
English_United States
English_United States.UTF8
en_US
en_US.windows-1252
1033

This all depended on what version of Python you are using. This is all sorted out for you and when you construct a wx.Locale instance it handles setting the locale in cpp code and also in python code.

Here is an updated version which solves an app crash issue, and also makes the LocaleName and CanonicalName properties of wx.LanguageInfo work properly.

[wx_locale.zip](https://github.com/wxWidgets/Phoenix/files/4536376/wx_locale.zip)

**Comment by josephsl** [comment]
Hi,

After testing the attached script and looking at 4.0.x git log, it appears it is indeed wx.Locale() that is to blame - 4.0.7 did add InitLocale but no issues there. So it appears something weird is going on with wx.Locale constructor (specifically, wx.Locale.Init).

I'm not sure if this is specific to wxPython or a companion issue should be filed on wxWidgets. If this is the latter, then I think this issue might be closed when wxWidgets submodule is updated by Robin provided that wxWidgets commit includes this fix.

Thanks.

**Comment by josephsl** [comment]
Hi,

Indeed, this is wxWidgets problem, evidenced by the fact that related locale.getlocale behaves correctly in 4.0.7post2.

Thanks (closing as it requires wxWidgets folks to look into this).

**Comment by kdschlosser** [comment]
@josephsl 

good luck getting it fixed on the wxWigets side. There have been open issues regarding the handling of the Locale on Windows for about 10 years now and it has not been fixed. I was just told a few months back that it wouldn't be fixed hence the reason why I made the patch.

**Comment by robertluwang** [comment]
Would you mind to tell wxWigets issue number for this?  Thanks.
