### ISSUE TITLE
4.1.0 includes unlisted breaking changes for sizer alignment flags 

### ISSUE THREAD

**Issue by chriskiehl** [wxWidgets/Phoenix#1612]
**Operating system**: Win10 Pro v1903 OS build: 18362.778
**wxPython version & source**:  4.1.0 msw (phoenix) 
**Python version & source**:  3.6.8 64 bit from python.org

**Description of the problem**:

The 4.1.0 includes an (unexpected?) breaking change that now throws errors for certain alignment flags. This causes applications to break when updating from 4.0.7 to 4.1.0. 

I'm curious if this was a planned breakage? I've looked over the [release notes](https://wxpython.org/news/2020-04-24-wxpython-410-release/index.html), but I don't see anything specifically called out as such. Similarly, running with `PYTHONWARNINGS=default` on 4.0.x shows no relevant warnings in my code base for this specific issue.  

The issue can be reproduced with the following code: 

```python
import wx

app = wx.App()

frame = wx.Frame(None, title='Simple application')
sizer = wx.BoxSizer(wx.HORIZONTAL)
sizer.Add(wx.StaticText(frame, -1, "foo"), 1, wx.ALIGN_CENTER_HORIZONTAL)

frame.Show()
app.MainLoop()
```

Traceback: 

```
Traceback (most recent call last):
  File "Gooey/gooey/examples/wxissue.py", line 7, in <module>
    sizer.Add(wx.StaticText(frame, -1, "foo"), 1, wx.ALIGN_CENTER_HORIZONTAL)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_HORIZONTAL)" failed at ..\..\src\common\sizer.cpp(2106) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```

**Comment by DarkFenX** [comment]
I am not a wx maintainer, but I assume they come from wxWidgets (rather than wxPython) since those are C++ assertions, and this as far as I understand it is development series of releases (4.2.x is supposed to be stable), so maybe some flags which help users of wx to properly use their API have been enabled during compilation.

I just ate that and went through every warning to get rid of them for my app.

**Comment by Metallicow** [comment]
ummm. yea some of the flags has deprecated/removed. Robin comfirmed this. I did a PullReqz not too long ago. I dont think there was anything added to the documentation. Probably should have been..

**Comment by Metallicow** [comment]
@chriskiehl See https://github.com/wxWidgets/Phoenix/pull/1272

**Comment by Metallicow** [comment]
@RobinD42  Could you write a little blurb in the Upgrading .rst that explains this small change. Thanks. It kinda was missed.

**Comment by RobinD42** [comment]
Yes, it's coming from wxWidgets, and yes, it's an intentional change. 

Basically the intent is to inform you that the flags you used are invalid. The change is that it is now validating the flags you pass instead of ignoring the error in your code. Granted, in this case it's not a fatal error or anything serious, but it is incorrect none the less.

**Comment by DietmarSchwertberger** [comment]
I'm currently adapting wxGlade to this and are almost done.

It's not nice to break things without a deprecation phase and causing a lot of additional work. It will probably cause a lot of frustration and support effort for projects that are using wx/Python.

(The additional work is required because multiple branches have to be changed. With a reasonable deprecation phase that's not required.)

I also don't understand the motivation of the change. Is wx still throwing a lot of gtk assertion messages? That would have been a more obvious target...

**Comment by RobinD42** [comment]
Generally wxWidgets does follow a "deprecation in one major.minor release and don't remove until the next major.minor release" type of policy, especially for API changes. But I think the difference in this case is that it is considered a bug-fix, not an API change or similar. Just because something incorrect was accidently allowed before does not make it become correct, and the fix to help the developer to **_not_** do things incorrectly is just that, a fix, not a bug.

In addition, it's been in the master branch of wxWidgets for 5 years! See https://github.com/wxWidgets/wxWidgets/commit/78b98bf00c8158f730a0360ca2873e1fa5634193, and so it's been in the wxPython 4.1 dev builds since day one. Granted it would have been better to give some kind of warning about this, but for those using the 4.1 dev builds it has been long enough since the initial pain needed to fix their code that it has become almost forgotten.

**Comment by RobinD42** [comment]
Also, wxWidgets uses an even/odd policy where the _minor_ version number series (3.1.0, 3.1.1, 3.1.2...) are considered _unstable_, not in the buggy sense, but in the sense that things can change in wxWidgets that require changes in the code of the developers using the library. In the even minor number series are stable and every effort is made to not make changes that would impact existing code.

I try to insulate Python users from the _unstable_ kinds of changes, but there isn't always an easy way to do that which doesn't also complicate things in future releases. One of the reasons for starting the Phoenix effort was to be able to get rid of all those kinds of stability and backwards compatibility hacks which had been collecting over the decades.

**Comment by DietmarSchwertberger** [comment]
Well, I don't know whether people usually bind statically to wx. In that case it's not a problem.

With wxPython almost nobody binds statically but defines a minimum required version.
On PyPi 4.1.0 is now default, not unstable/developer. So the deprecation phase was 0 days and many applications will just crash?
This will cost a lot of credibility.

**Comment by chriskiehl** [comment]
@RobinD42 Ah, thanks for that context and explanation of expectations! As a downstream consumer, the non-standard semantic versioning usage is definitely surprising and I think what led to the current woes of, from our perspective, software which suddenly broke when the version indicated that it shouldn't. Generally, minor and patch versions imply backwards compatibility. 

That said, as someone in the "semantic versioning is bad" camp, this is more of a problem with our collective unstated assumptions around what a version string means rather than your specific usage. Given that changes in Wx core are to some degree out of your hands, favoring your developer sanity and long-term maintainability over backward compatibility hacks that'd eventually crush forward progress strikes me as a smart way to run a project like this now that I understand the context. 

The only thing I'd ask, to better manage expectations, would you consider adding a small blurb to the site / README about expectations around API stability and what your release versions mean? This would help people consuming WxPython (like me!) to better manage how we approach onboarding new releases. As is, I kinda dumbly just specified a minimum version (as @DietmarSchwertberger pointed out). 

Finally, since Github issues can be a little coarse and about, well, _issues_, it'd be remiss if I didn't finish up with a giant "thanks!" The work you've put in over the course of _years_ is honestly astounding. Phoenix is an amazing project that allows a whole ecosystem of applications to thrive. [Gooey](https://github.com/chriskiehl/Gooey) certainly couldn't exist without it. You're doing awesome stuff here! ^_^

**Comment by Metallicow** [comment]
@chriskiehl 
Since you are using Windows and look to be in control of the requirements file it would probably be easier for you just to setup a wx.pth switching system. Robin used to have a script called wxversion that would sorta do this in code, but it didnt always work right and has since been retired.
Using my little utility after you get your versions extracted to correct "folder" makes hotswapping versions on the fly so much easier.
https://github.com/Metallicow/wxpthVersionSwitcher
Of course you have to edit your paths in the script and also download the .whl for each Relz and extract the wx directory from the whl into named directories.
```
C:\Python27\Lib\site-packages\wx-2.8-msw-unicode
C:\Python27\Lib\site-packages\wx-3.0-msw
C:\Python27\Lib\site-packages\wx-4.0.x-msw-phoenix
C:\Python27\Lib\site-packages\wx-4.1.x-msw
```
If you use pip to install wxPython it will just throw the wx directory straight into sitepackages, which isnt desired for multi version installs. So I avoid using pip for wxPython.
Having your requirements file specify a specific version simply states that "This version should work better than others" until you decide to change it.
Most other users will just use pip and it will grab 4.0.x or whatever version you need.
In the meantime devs can switch inbetween the 2(or more) wxPy versions at the click of a button(or unless you prefer to manually edit wx.pth with a text editor)
And now that Robin has released wxPy4.1.x to PyPI, you could even make an additional "Folder" called wx-4.1.x-msw-latest-snapshot which would now truly be "the bleeding edge".
Hope this helps.
The odd/even versioning thing has been like that for years, so yea, if you see a version jump just by .1, expect some sort or changes...(sometimes they break startup, so expect that from time to time)
