### ISSUE TITLE
documentation for GetPixel is missing notes for OSX

### ISSUE THREAD

**Issue by carandraug** [wxWidgets/Phoenix#1701]
`wx.MemoryDC.GetPixel` on OSX returns `(-1, -1, -1, 255)` for all pixels. There is no note on the wxPython documentation about it but looking into wxWidgets there is "This method isn't available for wxPostScriptDC or wxMetafileDC nor for any DC in wxOSX port and simply returns false there.".

This should probably not be lost on the conversion. I have found the code to change the documentation on `etg/dc.py` but I was wondering if there's a way to keep the original note and only change the bit that is required.

**Comment by swt2c** [comment]
Interesting.  Because the Python implementation isn't wrapping the C++ implementation exactly, you can't check the return value of GetPixel.  Perhaps the Python implementation should instead be throwing a "not implemented" exception on OSX after checking the C++ return value?

But yeah, the documentation probably could be retained.  Here's one place it is done:
https://github.com/wxWidgets/Phoenix/blob/master/etg/image.py#L169

**Comment by carandraug** [comment]
I know that I can't check the return value like on the wxWidgets where it returns a bool but the return value seems to be used to indicate that does not work. At least on OSX I have found that it returns `(-1, -1, -1, 255)` which is an invalid colour. I'm assuming that the invalid colour is the same as returning false from wxWidgets.

**Comment by swt2c** [comment]
I don't know.  Could just be garbage or some default values.

**Comment by RobinD42** [comment]
>  I'm assuming that the invalid colour is the same as returning false from wxWidgets.

Yes.

**Comment by RobinD42** [comment]
> > I'm assuming that the invalid colour is the same as returning false from wxWidgets.
> 
> Yes.

And, you can test it with `if` in Python, like this:

```
    pix_colour = dc.GetPixel(x,y)
    if pix_colour:
        do_something(pix_colour)
```
