### ISSUE TITLE
Catalina 10.15.6 + Python 3.8 Breaks wxPython 4.1.0

### ISSUE THREAD

**Issue by phirst** [wxWidgets/Phoenix#1738]
**Operating system**: macOS Catalina 10.15.6
**wxPython version & source**:          4.1.0 (pip install)
**Python version & source**:            Brew installed 3.8

**Description of the problem**:
Upgraded to Catalina and many things broke.  Existing application using Gooey functioned prior to upgrading to Catalina 10.15.6.

Starting the script `python3 myscript.py` now outputs this:
```
Initializing GUI...
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.

Fatal Error : C++ assertion "!(flags & wxALIGN_CENTRE_HORIZONTAL)" failed at /Users/robind/projects/bb2/dist-osx-py38/build/ext/wxWidgets/src/common/sizer.cpp(2106) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
Exiting...  Please check the log file for details.
```

Downgrading wxPython to 4.0.7 results in this:
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
```
but no fatal error.  Continues to run as expected.

**Comment by DietmarSchwertberger** [comment]
It's not a bug, it's a feature, unfortunately.
Unfortunately 4.1 activates many assertions due to underlying wxWidgets 3.1 "unstable".
See e.g. issue #1612 for discussion.
You have a horizontal sizer and are adding an item with `wxALIGN_CENTRE_HORIZONTAL`. This is not valid any more. Previous versions did ignore this. 4.1.0 will trigger an assertion.
There are many such combinations which will not work any more.

You may be able to avoid one or the other by calling  `wx.App.SetAssertMode(0)`.

**Comment by RobinD42** [comment]
FTR, this has been mentioned in the changlog for the next release:

```
* This should have been mentioned in the notes for the last release, but alas,
  it wandered away and got lost. wxWidgets is now validating the flags passed
  when adding items to a sizer, to ensure that they are the correct flags for
  the type of the sizer. If the given flags do not make sense, for example using
  horizontal alignment flags in a horizontal box sizer, then a wxAssertionError
  error is raised.
```
