### ISSUE TITLE
import ogl error

### ISSUE THREAD

**Issue by jonormand** [wxWidgets/Phoenix#1772]
**Operating system**: windows 10
**wxPython version & source**:          
**Python version & source**:     3.8.4       

**Description of the problem**: I can'nt import ogl in last wxPython build
with IDLE :

```python
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import wx
>>> wx.__version__
'4.1.1a1.dev4919+57702fa7'
>>> import wx.lib.ogl
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import wx.lib.ogl
  File "C:\Users\moi\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\lib\ogl\__init__.py", line 6, in <module>
    from .basic import *
  File "C:\Users\moi\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\lib\ogl\basic.py", line 3987, in <module>
    from .canvas import *
  File "C:\Users\moi\AppData\Local\Programs\Python\Python38\lib\site-packages\wx\lib\ogl\canvas.py", line 18, in <module>
    from .composite import *
ModuleNotFoundError: No module named 'wx.lib.ogl.composite'
>>>
```

**Comment by infinity77** [comment]
This is due to:

https://github.com/wxWidgets/Phoenix/commit/c00b8950da7736c67ee27b7a8006d6cf4a1ef613#diff-8bd22db578fac91ddaa024d07eb790e2

A “spelling correction” inside wx.lib.ogl.canvas that changed “composit” to “composite”. But the actual module is called “composit”, and it’s not a spelling mistake.

**Comment by swt2c** [comment]
Oh wow.  Yeah, that commit really ought to be reverted and done much more carefully.  It also changes variable names that were *not* misspellings.

**Comment by infinity77** [comment]
Agreed. One has to be careful while doing a PR that big - I’m all for correcting spelling mistakes in docstrings and comments, I am less ok with stylistic changes to code just for sake of “spelling correctness” - whatever that means for a variable name.

**Comment by infinity77** [comment]
Beside wx.lib.ogl.canvas, it seems to me that wx.lib.mixins.rubberband, wx.lib.floatcanvas.ScreenShot, wx.lib.ogl.basic, wx.lib.ogl.composit, wx.lib.ogl.divided are either broken or the meaning of the variables has been changed from their original intent.

**Comment by swt2c** [comment]
Yep, I also saw there was a file with an embedded image that got changed.  Surely that is now broken as well.

**Comment by RobinD42** [comment]
Oops, sorry about that guys. I used a code spellcheck tool and I thought it was only modifying comments and strings. Live and learn...

I've reverted that merge.

**Comment by Metallicow** [comment]
@RobinD42 I have a love/hate relationship with spellcheckers usually because of stuff it does like this. One of the main reasons I haven't included one in SourceCoder by default because you cannot trust it to make a decision for itself, and when dynamically generating code it will FAIL guaranteed 100% of the time. It's understandable if you are a writer, etc, but it tends to cause way more eye-strain by all the changes it tries to do is worse than PEP8 on speed. And since I don't work in the printshop anymore I cannot even hint to you that after the press printed 'one(that I was reading)' out and I read it that it was a typo...
...But just curious was it a released python spellchecking tool or mod/homebrew one?

**Comment by RobinD42** [comment]
https://github.com/codespell-project/codespell

I expected that it would only touch quoted strings and comments, and that seemed to be the case in the few test cases I looked closely at. Maybe there is an option to behave that way, if so then maybe I'll give it another try when I have some time.
