### ISSUE TITLE
wxPython 4.1 does not propagate MouseWheel event with WxAgg in MatPlotLib

### ISSUE THREAD

**Issue by michaelmarty** [wxWidgets/Phoenix#1794]
I posted this a while back to the MatPlotLib Issues. Reposting here because it was suggested that this was a wxPython issue: [https://github.com/matplotlib/matplotlib/issues/17513](https://github.com/matplotlib/matplotlib/issues/17513).

**Summary**

wxPython 4.1 is not propagating MouseWheel events with the WxAgg backend. The events seem to stop within the matplotlib canvas. Other wxPython controls are propagating it correctly with version wxPython 4.1, and everything works fine with wxPython 4.0.7.

**Code for reproduction**

```
import wx
import wx.lib.scrolledpanel as scrolled
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg
from matplotlib.figure import Figure

class PlottingWindow2(wx.Window):
    def __init__(self, *args, **kwargs):
        wx.Window.__init__(self, *args, **kwargs)
        self.figure = Figure(figsize=(6, 5))
        self.canvas = FigureCanvasWxAgg(self, -1, self.figure)
        self.Bind(wx.EVT_SIZE, self.size_handler)
        self.Bind(wx.EVT_MOUSEWHEEL, self.on_wheel)
        self.canvas.mpl_connect('scroll_event', self.on_scroll)

    def size_handler(self, *args, **kwargs):
        self.canvas.SetSize(self.GetSize())

    def on_scroll(self, event):
        print("MPL Scroll")

    def on_wheel(self, event):
        print("Canvas Scroll")
        event.Skip()

class MyFrame(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, title=title, size=(400, 400))
        plotwindow = scrolled.ScrolledPanel(self, -1)
        sizerplot = wx.BoxSizer(wx.VERTICAL)
        self.plot1 = PlottingWindow2(plotwindow)
        sizerplot.Add(self.plot1, 0, flag=wx.EXPAND)
        plotwindow.SetSizer(sizerplot)
        plotwindow.SetupScrolling()
        plotwindow.Bind(wx.EVT_MOUSEWHEEL, self.onWheel)
        self.Show(True)

    def onWheel(self, event):
        print("WX Scroll")
        event.Skip()

app = wx.App(False)
frame = MyFrame(None, "Test")
app.MainLoop()
```

**Actual outcome**

With wxPython 4.1.0, the scrolling does not work, and the console output is:

MPL Scroll

Note: the event does not propagate up. Other wxPython items like text controls propagate correctly.

**Expected outcome**

With wxPython 4.0.7, the scrolling works, and the console output is:

MPL Scroll
Canvas Scroll
WX Scroll

Note: the event propagates up correctly.

Matplotlib version

    Operating system: Windows 10
    Matplotlib version: 3.2.1
    Matplotlib backend (print(matplotlib.get_backend())): WxAgg
    Python version: 3.7.7
    Other libraries: wxPython 4.1.0 msw (phoenix) wxWidgets 3.1.4

Installed from pip

**Comment by Metallicow** [comment]
The jump wxPython did from 4.0 to 4.1 was quite a big one, and the only thing that is safe to assume here is that everyone involved is either right and wrong at same time depending on their usecase. In this case if matplotlib wants to be truely consistent across all platforms/OSs they understand that you will have to force something on either matplotlibs end or yours.
In my case when I jumped to wxPy4.1 I came across the facts that at one point I had to force something in order get it to work logically the way I want it to. Now that meant one thing wxPython is the mediator in my situation because I have my own personal modded copy of whatever widget needed improvement. wxWidgets on the other hand does not know if I am forcing something or not. In which case it is safe to assume you have just inverted your logic and your force fix is now (invalid, stacking, or ignored). So if you look at your code it will be quite obvious that it is a Event issue starting at the top that now allows you to do what wasn't possible before.

True/False/True  # you are either right and wrong at the same time here or 1 or the other. this is a range. think (1,2,3) and your error from what you stated is 2, therefore you are standing against both walls of your limits or you are in the middle. Which one is it?
False/True/False
Agg = +--
onWheel is not the same as OnWheel. Is this an override or not? Is super used?

My suggestion to you since this is a MouseWheel event is to look at my wxPython example in Main.py here https://github.com/Metallicow/wxPython-Sample-Apps-and-Demos
It attempts to override every widget class so that behavior is consistent across platforms. The handling of the mousewheel is done in the App class, but sometimes you may need to redirect your widget locally to the App OnMouseWheel method. Ex: STC and some other 3rd party integrations for whatever reasons need some guidance when bound(self.Bind(event, method)).
At that point you should make a decision if you are actually forcing something and if so, then you cannot lay the blame on any other party other than yourself because your code(or forked widget could not foretell the future that wxWidgets would someday implement the fix itself, which makes one or the other not needed anymore or you need to write another function to handle your multiplication in example usecase)
Hope this helps.

**Comment by swt2c** [comment]
This may be MSW specific.  I can't seem to reproduce this on GTK.  I'm using a laptop without a mouse, but I think two finger scrolling on the touchpad should act like the scroll wheel.  I see all three messages.  Have you seen this on any platform other than MSW?

**Comment by Metallicow** [comment]
Also note with my correct logic of the situation...
Hmmmm how should I explain this. might as well be truthful...
If I drop a Walrus on top of your head :=
then yes, I can even defy your own logic most times.
THIS COULD BE DANGEROUS! This is why Guido said no to the walrus. 
It does have usecases but only if you understand what you are really trying to do.
BTW I voted for Guido.

**Comment by RobinD42** [comment]
Since `wx.MouseEvent` is not a `wx.CommandEvent` it doesn't actually propagate, and that is by design. What appears to be happening is that the event is sent more than once from different sources, at least on OSX where I'm testing at the moment. If you change your print's to be like this:

```
        print("Canvas Scroll:", event.GetEventObject())
# and 
        print("WX Scroll:", event.GetEventObject())
```

Then you'll see messages like this:

```
Canvas Scroll: <__main__.PlottingWindow2 object at 0x7fe658131a60>
WX Scroll: <wx.lib.scrolledpanel.ScrolledPanel object at 0x7fe658131940>
```

The platform difference is probably due to differences in the implementations of `wx.ScrolledWindow` or helpers.

Since mouse events are not supposed to propagate then my suggestion would be to continue to catch the wheel event in the canvas, and then create and send a custom event object using a class that derives from `wx.CommandEvent` and carries whatever information you would like the class(es) further up in the hierarchy to see. Using `wx.lib.newevent` can help with the custom event class and binder object, and sending the event can be done with `self.GetEventHandler().ProcessEvent()'. That will give you behavior that is functionally equivalent to what would happen if the wheel event did propagate.
