### ISSUE TITLE
Grid cell will lose focus by mouse motion

### ISSUE THREAD

**Issue by jnhyperion** [wxWidgets/Phoenix#1797]
**Operating system**: Mac Catalina
**wxPython version & source**:         4.1.0
**Python version & source**:            3.8

**Description of the problem**:

1. Double click a cell, OnEditorCreated & OnEditorShown will be triggered
2. Move mouse out of the cell's boundary, the focus on cell will be dismissed automatically (OnEditorHidden is triggered automatically)

Expect:

Cell will not lose focus by mouse motion.

**Comment by RobinD42** [comment]
I don't have a machine with Catalina on it at the moment... Does it also happen to you if you try one of the grid samples in the demo? Do you have anything in your application that is reacting to mouse motion events or focus events? Do you have any accessibility options turned on that might be interfering, or perhaps some focus-follows-mouse utility?

**Comment by jnhyperion** [comment]
I found it also happens in windows, I tested in wxDemo simple grid.

In 4.0.7.post2, it does not have this issue.

![4_0_7_post2](https://user-images.githubusercontent.com/20297196/95937803-2ac64c80-0e0b-11eb-9b91-0e42e27944c5.gif)

Broken in 4.1.0:

![4_1_0](https://user-images.githubusercontent.com/20297196/95937872-4a5d7500-0e0b-11eb-9535-8c66554f3e86.gif)

**Comment by RobinD42** [comment]
I was not able to duplicate this on a Mac, and on Windows it only happens when I happened to move the mouse over another application that has the bad behavior of activating/raising itself and taking the focus. Since the grid cell editors will automatically close when they lose the focus then it's possible that you also have something that is taking the focus somehow.

**Comment by cbeytas** [comment]
Issue happens for me too, Windows 7 and Windows 10. Python 2.7 and python 3.8.
wxPython v4.0.7.post2 is fine. Issue only present on wxPython v4.1.0

The loss of focus only happens when the mouse hits a cell boundary and changes to the Resizing cursor.
If you disable resizing with `grid.DisableDragGridSize()` the issue goes away (unless you mouse over a header or column label boundary).

**Comment by Metallicow** [comment]
Confirmed.
Yep, yet another focus bug/fix issue related to the wxPy 4.1 wxWidgets underlying event changes.
wxPy4.0 will work fine for you. Depending on if the widget is a C widget or a python widget, the time it takes to upgrade the widget to work with the new event based changes might vary.
If it is a python widget you can try to apply your own workaround until 4.1.x+ but if it is a C widget then you will either need to wait for the wxWidgets end to adapt or work with them to provide a patch.

**Comment by jnhyperion** [comment]
@Metallicow @RobinD42 verified, this issue has been fixed in 4.1.1.

**Comment by Jorilx** [comment]
> verified, this issue has been fixed in 4.1.1.

@jnhyperion I'm sorry, could you point out which commit fixed the issue? Or where I could search for it? Many thanks!
