### ISSUE TITLE
wx.GraphicsContext.DrawText not working properly

### ISSUE THREAD

**Issue by kdschlosser** [wxWidgets/Phoenix#1815]
**Operating system**: Windows 7 x64
**wxPython version & source**: 4.0.7.post1 msw (phoenix) wxWidgets 3.0.5 (pypi)
**Python version & source**: 3.7.5 Stackless 3.7 (tags/v3.7.5-slp:f7925f2a02, Oct 20 2019, 15:28:53) [MSC v.1916 64 bit (AMD64)]

**Description of the problem**:
The overloaded DrawText(str, x, y, angle) does not render the text at proper angles. The angles it is rendering the text are off by a factor of angle * 0.075 so as the angle gets further away from 0 either + or - the worse the problem gets

The calculation to correct the angle of rotation is
``` python
degree = 180.0
degree -= (degree * 0.075)
```

```python
import wx
import sys

print(wx.version())
print(sys.version)


class Frame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, size=(600, 600))

    def render(self):
        dc = wx.ClientDC(self)
        gc = wx.GraphicsContext.Create(dc)
        gc.SetAntialiasMode(wx.ANTIALIAS_DEFAULT)
        gc.SetBrush(gc.CreateBrush(wx.Brush(wx.Colour(0, 0, 0, 255))))
        gc.DrawRectangle(0, 0, 600, 600)

        font = self.GetFont()
        font.SetPointSize(20)
        
        gc.SetFont(font, wx.Colour(255, 255, 255, 255))
        gc.DrawText('NOT ADJUSTED', 50.0, 25.0, 0.0)

        for degree, colour in (
                (0, (255, 255, 255, 255)),
                (90, (255, 0, 0, 255)), 
                (180, (0, 255, 0, 255)), 
                (270, (0, 0, 255, 255)), 
                (360, (0, 255, 255, 127))
        ):
            gc.SetFont(font, wx.Colour(*colour))

            gc.DrawText(str(degree) + '°', 150.0, 150.0, degree)
            gc.DrawText(str(-degree)+ '°', 350.0, 150.0, -degree)

        gc.SetFont(font, wx.Colour(255, 255, 255, 255))
        gc.DrawText('ADJUSTED', 50.0, 250.0, 0.0)

        for degree, colour in (
            (0, (255, 255, 255, 255)), 
            (90, (255, 0, 0, 255)), 
            (180, (0, 255, 0, 255)),
            (270, (0, 0, 255, 255)),
            (360, (0, 255, 255, 127))
        ):
            gc.SetFont(font, wx.Colour(*colour))

            degree -= (degree * 0.075)
            gc.DrawText(str(degree)+ '°', 150.0, 400.0, degree)
            gc.DrawText(str(-degree)+ '°', 350.0, 400.0, -degree)


        gc.Destroy()
        del gc

        dc.Destroy()
        del dc

app = wx.App()
frame = Frame()

frame.Show()
frame.render()

app.MainLoop()
```

**Comment by kdschlosser** [comment]
This problem is a lot more involved.
While my fix does work for 90 degree increments it does not work as a whole.

If you set the angle to 80.0 and render the text and then set it to 70.0 and render the text you end up with the following.

The red dots are the point the text is rotated around.
![image](https://user-images.githubusercontent.com/10932297/95695641-1c064c80-0bf5-11eb-9102-796cd6dd5680.png)

**Comment by kdschlosser** [comment]
Yup it takes radians.

I am not going to close this issue because there is a bug, it's in the documentation. It doesn't specify that the angle has to be in radians. this needs to be added.

**Comment by Metallicow** [comment]
ummm yea, I had a bit of issues when I was porting all the demos with this type of stuff. But yes all we can really do is when someone revisits each case is to go ahead and update the docs to be better written or add a note to the func/method when sphinx generates the docs.
We really should have a liquid_wxPy.html page in the reference docs pages also that might help people with this stuff.
for example acronyms and just basic terminology would be included on the page so a new user who may not be familiar with wxWidget/C++ or Python/Py can at least try to take an educated guess at what it should be.  A lot of people often ask what ctor means or what the m_ is supposed to mean with attributes naming. Also you will notice int is a python thing in the docs but string is not. in python 2 it could be confused with a module but might be better generated to read str. Also since python is interpreted bool could actually be a string or an int/ float or True/False, etc... so yea this is kinda why doing the docs takes a bit of time to try and get everything explained right.

**Comment by swt2c** [comment]
The documentation comes from wxWidgets.  I submitted a pull request to clarify the units for DrawText.

**Comment by kdschlosser** [comment]
Fantastic. I do thank you for doing that. I don't imagine there are to many people using wx.GraphicsContext. but for those that are knowing the proper units are handy.

**Comment by RobinD42** [comment]
The last update of the wxWidgets submodule included that change.
