### ISSUE TITLE
wxPython 4.1.1 - selecting a single Grid row does not work

### ISSUE THREAD

**Issue by jrobijns** [wxWidgets/Phoenix#1892]
**Operating system**: Windows 10 & macOS Big Sur
**wxPython version & source**:          V4.1.1, pypi
**Python version & source**:            V3.9.0 distro (MacOS) & V3.8.5 (Windows 10)

**Description of the problem**: I set up a wx.grid.Grid, with SetSelectionMode(wx.grid.Grid.SelectRows). The the OnGridRangeSelect event, I check which rows are selected by inspecting .SelectedRows. In wxPython 4.1.0 this works fine.
After upgrading to wxPython 4.1.1, something weird happens:
- When selecting 1 row, the event triggers and the list of selected rows is empty
- When selecting multiple rows, the event triggers and the list is correct (including the one that didn't select on its own)
- When command-selecting (MacOS) or shift-selecting a single row, it DOES show up in the list.

Tested it on macOS Catalina and Big Sur and Windows 10. Different Python versions. I think it has to be wxPython.
Unfortunately 4.1.1 fixes a problem with missing events when clicking a bitmap on MacOS, so I do want to upgrade.
But I need single-select for rows more :-/

I think it is pretty self-explanatory, but if needed I will create sample code.

**Comment by RobinD42** [comment]
There were some changes related to grid selections a while back, although I don't recall the details. After playing with one of the grid samples in the demo I see that the range-select event you get when selecting one row by clicking on a cell is actually a _deselection_ event for the whole grid. In other words, before making the new selection it clears any new selections first.

After that I see a `EVT_GRID_SELECT_CELL` event for the row and no event for the whole range of the row. That does make some sense since it was only one cell selected by the user and then the grid draws the selection highlight for the whole row. The range only comes into play when you do things to really select the whole row, like clicking on the row label or doing a {modifier}-click.

So although the change does cause a bit of disruption for you, I think it is a bit more consistent than it was before, and there is a workaround available for you. You can catch `EVT_GRID_SELECT_CELL` in addition to `EVT_GRID_RANGE_SELECT` and deal with the single selections separately.

**Comment by jrobijns** [comment]
Thanks for the extensive reply, Robin! I did as you suggested and it works like a charm :-)
