### ISSUE TITLE
wx.dataview.TreeListCtrl incompatible with VirtualTree mixin

### ISSUE THREAD

**Issue by petrasovaa** [wxWidgets/Phoenix#202]
It's unclear to me whether wx.dataview.TreeListCtrl is supposed to be working with wx.lib.mixins.treemixin.VirtualTree. TreeListCtrl was taken out of the TreeMixin demo, so I tried to put it back, but I get:

```
Traceback (most recent call last):
  File "/home/anna/dev/Phoenix/demo/TreeMixin.py", line 232, in OnPageChanged
    newTree.RefreshItems()
  File "/home/anna/dev/Phoenix/wx/lib/mixins/treemixin.py", line 371, in RefreshItems
    self.RefreshChildrenRecursively(rootItem)
  File "/home/anna/dev/Phoenix/wx/lib/mixins/treemixin.py", line 389, in RefreshChildrenRecursively
    reusableChildren = self.GetItemChildren(item)
  File "/home/anna/dev/Phoenix/wx/lib/mixins/treemixin.py", line 240, in GetItemChildren
    child, cookie = self.GetFirstChild(item)
TypeError: 'TreeListItem' object is not iterable
```

Is this something to be fixed for the release? Or VirtualTree can't be used with TreeListCtrl anymore? What's the alternative?

**Comment by RobinD42** [comment]
The TreeListCtrl in the dataview module is not the same as the old gizmos.TreeListCtrl, which hasn't been ported yet, so it's not intended to be compatible with the VirtualTree class.

I'm not planning on adding the gizmos module to Phoenix because the C++ code was not well maintained the last time I checked on it, but I would be happy if somebody decided to port some of those classes to pure python implementations.

**Comment by RobinD42** [comment]
See #302

**Comment by mesalu** [comment]
Looks like TreeListCtrl has been ported as pure python.
