### ISSUE TITLE
wx.html2.WebView NotImplementedError (Ubuntu GTK)

### ISSUE THREAD

**Issue by Patitotective** [wxWidgets/Phoenix#2028]
**Operating system**: Ubuntu 20.04
**wxPython version & source**: 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5 (built wheel from PyPi). 
**Python version & source**: Python 3.9.5. 

### Description of the problem
I'm trying to implement a loading spinner animation as html and css into a `wx.html2.WebView` but I'm getting `NotImplementedError`.
I've found two other persons having the same issue: [Chapter 6: NotImplemented](https://github.com/Johnnyboycurtis/wxtutorials/issues/1) and [Why is it not available in CentOS wx.html2 . WebView control？](https://stackoverflow.com/questions/66283225/why-is-it-not-available-in-centos-wx-html2-webview-control)

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx
from wx.html2 import WebView


class MyFrame(wx.Frame):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        browser = WebView.New(self)

        self.Show()


if __name__ == "__main__":
    app = wx.App()
    frame = MyFrame(parent=None)
    app.MainLoop()
```
</details>

**Comment by swt2c** [comment]
I just answered that stackoverflow post, but here's a slightly modified response for Ubuntu:

`NotImplementedError` means that wxPython was compiled without `wx.html2` support. The most likely cause of this on Linux is that the WebKit2 development packages were not present when you installed/compiled wxPython. To resolve this, install the WebKit2 development package and reinstall wxPython. On Ubuntu, the WebKit2 development package is `libwebkit2gtk-4.0-dev`, so install it with the package manager, e.g., `apt install libwebkit2gtk-4.0-dev` and then uninstall/reinstall wxPython. Note: you may have to also clear the pip cache so that it won't re-use the previously compiled version of wxPython.

**Comment by Patitotective** [comment]
Thanks @swt2c for the answer, it worked.
(Although it took kinda 1 to build the wheel)
