### ISSUE TITLE
On Python 3.10: TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by cykerway** [wxWidgets/Phoenix#2038]
**Operating system**: Fedora 35
**wxPython version & source**:         4.0.7 
**Python version & source**:           3.10 

**Description of the problem**:

After install wxpython using:

    dnf install python3-wxpython4

The example code throws:

>   TypeError: 'float' object cannot be interpreted as an integer

There is something very interesting: The fc35 package leaves its files at `/usr/lib64/python3.10/site-packages`. However, I didn't find 3.10 a supported Python version in wxpython `setup.py` (version 4.0.7, but same in master). Would you please confirm if wxpython will work with Python 3.10 on the Linux platform (Fedora, in specific)?

-   If answer is "yes", then what caused the exception?

-   If answer is "no", then it looks like Fedora maintainers are making a mistake by giving a 3.10 package? I can forward the issue there instead.

<details>
  <summary>Code Example (click to expand)</summary>

```python
#!/usr/bin/env python3

from wx.lib.agw.pygauge import PyGauge
import wx

class MyFrame(wx.Frame):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self.gauge = PyGauge(self, range=128)

app = wx.App()
MyFrame(None).Show(True)
app.MainLoop()

```
</details>

**Comment by swt2c** [comment]
Thanks for the report.  Officially, I suppose wxPython doesn't support Python 3.10 *yet* but the Fedora package should be mostly working.  In this case, you've found a Python 3.10 bug with PyGauge.  I'll submit a fix for it (and let me know if you want it fixed in Fedora, too).

**Comment by cykerway** [comment]
Thanks for quick response. I believe you can find more such bugs in `ListCtrl`, etc. It's somewhat ubiquitous because the float is introduced by a division `/`, which is everywhere in wxpython widgets source code. In Python 3.x a division always gives a float, but this assignment works with Python 3.9...

I have compared the shipped files in old and new RPMs. They turn out to be almost exactly the same (except for some build IDs). This implies the problem doesn't like in `.py` files but somewhere more fundamental. For this specific thread, I'm wondering why assigning a float to an int would work when using Python 3.9 but not 3.10.

**Comment by swt2c** [comment]
> Thanks for quick response. I believe you can find more such bugs in ListCtrl, etc. It's somewhat ubiquitous because the float is introduced by a division /, which is everywhere in wxpython widgets source code. In Python 3.x a division always gives a float, but this assignment works with Python 3.9...

You are right, there are quite a few of them.  I'll try to fix as many of them as I can.

> I have compared the shipped files in old and new RPMs. They turn out to be almost exactly the same (except for some build IDs). This implies the problem doesn't like in .py files but somewhere more fundamental. For this specific thread, I'm wondering why assigning a float to an int would work when using Python 3.9 but not 3.10.

It was a change in Python 3.10 to the extension module interface - you can no longer pass a float to an extension function (i.e., a wrapped wxWidgets C++ function) where an int is expected and there would be truncation.  You can of course still do that in pure Python.

**Comment by swt2c** [comment]
Okay, I think I fixed most of the Python 3.10 issues.  Once merged, I'll plan to backport this fix to Fedora.

**Comment by cykerway** [comment]
Nice job! That's indeed "quite a few"!

It seems all changes (except demos) happen in `wx.lib`. What exactly is this module? Does this contain pure-python widget implementations? I previously thought wxPython is a thin wrapper on wxWidgets, but from your changes it seems it ships pure-python widgets by itself, too?

One example is `auibook`, which is available in both wxPython and wxWidgets. But the wxPython implementation file has thousands of lines. I guess this is not merely a wrapper? Are they the same thing?

**Comment by swt2c** [comment]
> It seems all changes (except demos) happen in wx.lib. What exactly is this module? Does this contain pure-python widget implementations? I previously thought wxPython is a thin wrapper on wxWidgets, but from your changes it seems it ships pure-python widgets by itself, too?

> One example is auibook, which is available in both wxPython and wxWidgets. But the wxPython implementation file has thousands of lines. I guess this is not merely a wrapper? Are they the same thing?

`wx.lib` is additional modules that are written in pure Python.  A lot of them seem to duplicate functionality that exists in wxWidgets, while others provide additional functionality.  I don't know the history behind why the duplicative ones exist - perhaps they existed before the functionality was implemented in wxWidgets?  My personal recommendation would be the use the wrapped C++ modules as much as possible as that code base is much better maintained than the pure-Python code.

**Comment by cykerway** [comment]
Alright, that explains. As I said, I previously thought wxPython is a wrapper and this kind of issue shouldn't bring in this many LOCs. The situation is obviously different if they are full-blown implementations.

Thanks again for your work. Hope this gets reflected in upstream soon. You are free to close this issue, or invite Robin to start a lecture about pure-python widgets history here.

**Comment by infinity77** [comment]
> > It seems all changes (except demos) happen in wx.lib. What exactly is this module? Does this contain pure-python widget implementations? I previously thought wxPython is a thin wrapper on wxWidgets, but from your changes it seems it ships pure-python widgets by itself, too?
> 
> > One example is auibook, which is available in both wxPython and wxWidgets. But the wxPython implementation file has thousands of lines. I guess this is not merely a wrapper? Are they the same thing?
> 
> `wx.lib` is additional modules that are written in pure Python. A lot of them seem to duplicate functionality that exists in wxWidgets, while others provide additional functionality. I don't know the history behind why the duplicative ones exist - perhaps they existed before the functionality was implemented in wxWidgets? My personal recommendation would be the use the wrapped C++ modules as much as possible as that code base is much better maintained than the pure-Python code.

I would tend to disagree with you on this one: most of the stuff that lives in wx.lib is there to extend the functionalities of some wxWidgets control - or to provide widgets that are simply unavailable in the C++ implementation.
However, some of those pure-Python implementations exist *because* of the sorry state some of the wxWidgets controls have been for quite a long time. And because we can fix any bug that appears quickly and painlessly, without waiting for months and years for the wxWidgets developers to make up their minds. And we can extend them without delving into C++ code and recompile everything.

I could bet that some of the stuff in wx.lib is much more used and tested in real world applications than the actually wrapped C++ counterparts.

**Comment by swt2c** [comment]
@infinity77's probably a better person to weigh in on the pure Python modules as he wrote most of them.  :-)

> I would tend to disagree with you on this one: most of the stuff that lives in wx.lib is there to extend the functionalities of some wxWidgets control - or to provide widgets that are simply unavailable in the C++ implementation.
However, some of those pure-Python implementations exist because of the sorry state some of the wxWidgets controls have been for quite a long time. And because we can fix any bug that appears quickly and painlessly, without waiting for months and years for the wxWidgets developers to make up their minds. And we can extend them without delving into C++ code and recompile everything.

Fair point.  I'm just judging based on the amount of *current* developer activity that wxWidgets has vs wxPython.  I think the dynamic has also changed now that Robin is tracking the wxWidgets master branch, instead of wxWidgets *releases* which are few and far between.  wxWidgets bugs get fixed relatively quickly in the master branch (but not necessarily in a release), whereas wxPython bugs are currently getting fixed very slowly.

> I could bet that some of the stuff in wx.lib is much more used and tested in real world applications than the actually wrapped C++ counterparts.

Could be, hard to know for sure.

@infinity77 do you care to take a look at my PR #2039 ?

**Comment by bomm** [comment]
On Ubuntu 22.04.1 LTS, I installed the packages from the upcoming Ubuntu 23.04 Lunar Lobster version which are based on wxPython 4.2.0 and wxWidgets 3.2.1, in order to fix some problems with EasyABC (https://github.com/jwdj/EasyABC/issues/63).

I still notice some problems with GUI elements placed all in the top left corner and error messages like this:
~~~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/rcsizer.py", line 153, in CalcMin
    size = wx.Size( reduce( operator.add, self.colWidths),
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/rcsizer.py", line 163, in RecalcSizes
    minWidth, minHeight  = self.CalcMin()
  File "/usr/lib/python3/dist-packages/wx/lib/rcsizer.py", line 153, in CalcMin
    size = wx.Size( reduce( operator.add, self.colWidths),
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
```
This might be related to this issue.

**Comment by Apteryks** [comment]
@swt2c hi!  

It's seems there's still one such issue at least at line 380 in pygauge.py:
```
Traceback (most recent call last):
  File "/gnu/store/52578vcws4dkf668kxsqssjfmqycm78s-profile/lib/python3.10/site-packages/wx/lib/agw/pygauge.py", line 380, in OnPaint
    dc.DrawText(drawString, textXPos, textYPos)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float
  ```
  
That's part of the latest 4.2.0 release.

**Comment by Apteryks** [comment]
@swt2c Fixed in https://github.com/wxWidgets/Phoenix/pull/2387.
