### ISSUE TITLE
Failed to compile from source sip_propgridwxPGVIterator.cpp generated code

### ISSUE THREAD

**Issue by freakyd** [wxWidgets/Phoenix#231]
I tried to compile from the github source, but the sip code that is generated fails to compile. Compiling wx works fine, I am using python 2.7.13 and latest sip 4.19 from source.
../../../sip/cpp/sip_propgridwxPGVIterator.cpp:187:53: error: invalid static_cast from type ‘wxPGVIterator*’ to type ‘wxRefCounter*’
         return static_cast< ::wxRefCounter *>(sipCpp);

**Comment by RobinD42** [comment]
freakyd wrote:
>
> I tried to compile from the github source, but the sip code that is
> generated fails to compile. Compiling wx works fine, I am using python
> 2.7.13 and latest sip 4.19 from source.
> ../../../sip/cpp/sip_propgridwxPGVIterator.cpp:187:53: error: invalid
> static_cast from type ‘wxPGVIterator*’ to type ‘wxRefCounter*’
> return static_cast< ::wxRefCounter *>(sipCpp);
>

I'm currently using a pre-release snapshot of sip, as it has some fixes
for issues like this and some other issues, as well as a new feature
that I submitted. The version I'm using is 4.19.1.dev1702021705,
although it looks like there has been another snapshot made since then.

If you build from the source tarball instead of git then you will not
need sip (unless you make changes that require the .sip files to be
regenerated.)

-- 
Robin Dunn
Software Craftsman
http://wxPython.org

**Comment by freakyd** [comment]
Hey, thanks for the sip tip. Unfortunately I couldn't build any version, including the source tarball. I forget what failure it had. I used the latest sip snapshot which worked excellent and I got phoenix installed from the latest github source. The DeselectRow works perfectly, thanks a lot!
