### ISSUE TITLE
Patch release for 4.2.0 to remove `attrdict` module dependency wheel install failure

### ISSUE THREAD

**Issue by junwoo091400** [wxWidgets/Phoenix#2325]
**Operating system**: Ubuntu 22.04
**wxPython version & source**: PyPi
**Python version & source**: Python 3.10.6

**Description of the problem**:
As described in this issue very well: https://github.com/wxWidgets/Phoenix/issues/2225, current install of `wxpython` version 4.2.0 (https://pypi.org/project/wxPython/4.2.0/) fails, due to missing dependency to `attrdict` module, imported here: https://github.com/wxWidgets/Phoenix/blob/b567d1e6e3aff88f900d5ec4fb148531746b211d/buildtools/config.py#L30

**Proposed Solution**
To me, it seems like cherry picking this commit: https://github.com/wxWidgets/Phoenix/commit/2e9169effa9abf14f34f8436a791b8829eea7774, to the 4.2.0 release (https://github.com/wxWidgets/Phoenix/releases/tag/wxPython-4.2.0), and doing a patch release would solve the problem.

**Note**
However, I am also wondering, since the dependency is needed in `buildtools/config.py`, wouldn't this dependency fit better in `requirements/intall.txt`, instead of `devel.txt`?

E.g. here: https://github.com/wxWidgets/Phoenix/commit/2e9169effa9abf14f34f8436a791b8829eea7774#diff-48561a6ac9f59b3b79790238a78d2c345125e61834588671ac55f3fdafe1cd58R24

**Comment by Himura2la** [comment]
This issue affects me

**Comment by JacobHayes** [comment]
Even if you ensure `attrdict` is installed, it is not compatible with python 3.10+ as `from collections import Mapping` was moved to `from collections.abc import Mapping`.

**Comment by h00man** [comment]
Broken here too. Tried uninstalling and installing attrdict. Same for attrdict3. 
Lubuntu 22.10
Python 3.10.7

(my_py3_venv) mike@mike-vostro3460:~/my_py3_venv/bin$ pip install attrdict3
Requirement already satisfied: attrdict3 in /home/mike/my_py3_venv/lib/python3.10/site-packages (2.0.2)
Requirement already satisfied: six in /home/mike/my_py3_venv/lib/python3.10/site-packages (from attrdict3) (1.16.0)
(my_py3_venv) mike@mike-vostro3460:~/my_py3_venv/bin$ pip uninstall attrdict3
Found existing installation: attrdict3 2.0.2
Uninstalling attrdict3-2.0.2:
  Would remove:
    /home/mike/my_py3_venv/lib/python3.10/site-packages/attrdict3-2.0.2.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled attrdict3-2.0.2
(my_py3_venv) mike@mike-vostro3460:~/my_py3_venv/bin$ pip install attrdict3
Collecting attrdict3
  Using cached attrdict3-2.0.2-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: six in /home/mike/my_py3_venv/lib/python3.10/site-packages (from attrdict3) (1.16.0)
Installing collected packages: attrdict3
Successfully installed attrdict3-2.0.2
(my_py3_venv) mike@mike-vostro3460:~/my_py3_venv/bin$ pip install wxpython
Collecting wxpython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (9.4.0)
Requirement already satisfied: six in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (1.16.0)
Requirement already satisfied: numpy in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (1.24.2)
Installing collected packages: wxpython
  DEPRECATION: wxpython is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559                                                                                                 
  Running setup.py install for wxpython ... error                                                                                                   
  error: subprocess-exited-with-error
  
  × Running setup.py install for wxpython did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]
      /home/mike/my_py3_venv/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      /home/mike/my_py3_venv/lib/python3.10/site-packages/setuptools/dist.py:300: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running install
      /home/mike/my_py3_venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/home/mike/my_py3_venv/bin/python3" -u build.py build
      /tmp/pip-install-22cjtutj/wxpython_5b1501dcbdae46f29b8e8db86d80e310/build.py:43: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.dep_util import newer, newer_group
      Will build using: "/home/mike/my_py3_venv/bin/python3"
      3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.0
      
      Running command: build
      Running command: build_wx
      wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
      Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
      /tmp/pip-install-22cjtutj/wxpython_5b1501dcbdae46f29b8e8db86d80e310/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
      checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking for toolkit... gtk
      checking for gcc... gcc
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc accepts -g... yes
      checking for gcc option to accept ISO C89... none needed
      checking whether we are using the Intel C compiler... no
      checking how to run the C preprocessor... gcc -E
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for egrep... /usr/bin/grep -E
      checking whether gcc needs -traditional... no
      checking for g++... g++
      checking whether we are using the GNU C++ compiler... yes
      checking whether g++ accepts -g... yes
      checking whether we are using the Intel C++ compiler... no
      checking whether we are using the Sun C++ compiler... no
      checking for ar... ar
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking for langinfo.h... yes
      checking for wchar.h... yes
      checking for sys/select.h... yes
      checking for cxxabi.h... yes
      checking for an ANSI C-conforming const... yes
      checking for inline... inline
      checking size of short... 2
      checking size of void *... 8
      checking size of int... 4
      checking size of long... 8
      checking size of size_t... 8
      checking size of long long... 8
      checking size of wchar_t... 4
      checking for va_copy... yes
      checking for _FILE_OFFSET_BITS value needed for large files... 64
      checking if large file support is available... yes
      checking for _LARGEFILE_SOURCE value needed for large files... no
      checking whether byte ordering is bigendian... no
      checking for std::wstring in <string>... yes
      checking for std::istream... yes
      checking for std::ostream... yes
      checking for type_traits... yes
      checking for __sync_xxx_and_fetch builtins... yes
      checking for libraries directories... /usr/lib/x86_64-linux-gnu /usr/lib
      checking for cos... no
      checking for floor... no
      checking if floating point functions link without -lm... no
      checking for sin... yes
      checking for ceil... yes
      checking if floating point functions link with -lm... yes
      checking for strtoull... yes
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for LIBPCRE... yes
      checking for zlib.h >= 1.1.4... yes
      checking for zlib.h... (cached) yes
      checking for deflate in -lz... yes
      checking for png.h > 0.90... no
      checking for png.h... (cached) no
      configure: WARNING: system png library not found or too old, will use built-in instead
      checking whether png.c file exists... yes
      checking for jpeglib.h... no
      configure: WARNING: system jpeg library not found, will use built-in instead
      checking whether jpeglib.h file exists... yes
      checking for jbg_dec_init in -ljbig... no
      checking for LIBTIFF... not found via pkg-config
      checking for tiffio.h... no
      configure: WARNING: system tiff library not found, will use built-in instead
      checking whether tiff.h file exists... yes
      checking for expat.h... yes
      checking if expat.h is valid C++ header... yes
      checking for XML_ParserCreate in -lexpat... yes
      checking for LIBCURL... not found
      checking for GTK+ version...
      checking for pkg-config... (cached) /usr/bin/pkg-config
      checking pkg-config is at least version 0.16... yes
      checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gtk+-3.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gtk+-3.0' found
      no
      *** Could not run GTK+ test program, checking why...
      *** The test program failed to compile or link. See the file config.log for the
      *** exact error that occurred. This usually means GTK+ is incorrectly installed.
      configure: error:
      The development files for GTK+ were not found. For GTK+ 2, please
      ensure that pkg-config is in the path and that gtk+-2.0.pc is
      installed. For GTK+ 1.2 please check that gtk-config is in the path,
      and that the version is 1.2.3 or above. Also check that the
      libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
      --libs' are in the LD_LIBRARY_PATH or equivalent.
      
      Error running configure
      ERROR: failed building wxWidgets
      Traceback (most recent call last):
        File "/tmp/pip-install-22cjtutj/wxpython_5b1501dcbdae46f29b8e8db86d80e310/build.py", line 1563, in cmd_build_wx
          wxbuild.main(wxDir(), build_options)
        File "/tmp/pip-install-22cjtutj/wxpython_5b1501dcbdae46f29b8e8db86d80e310/buildtools/build_wxwidgets.py", line 379, in main
          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
        File "/tmp/pip-install-22cjtutj/wxpython_5b1501dcbdae46f29b8e8db86d80e310/buildtools/build_wxwidgets.py", line 72, in exitIfError
          raise builder.BuildError(msg)
      buildtools.builder.BuildError: Error running configure
      Finished command: build_wx (0m5.390s)
      Finished command: build (0m5.390s)
      Command '"/home/mike/my_py3_venv/bin/python3" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxpython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by h00man** [comment]
Broken here too. Tried uninstalling and installing attrdict. Same for attrdict3. Tried the '--use-pep517' option. 
Running Lubuntu 22.10, and Python 3.10.7

$ pip install wxpython
Collecting wxpython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pillow in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (9.4.0)
Requirement already satisfied: six in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (1.16.0)
Requirement already satisfied: numpy in /home/mike/my_py3_venv/lib/python3.10/site-packages (from wxpython) (1.24.2)
Installing collected packages: wxpython
  DEPRECATION: wxpython is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559                                                                                                 
  Running setup.py install for wxpython ... error                                                                                                   
  error: subprocess-exited-with-error
  
  × Running setup.py install for wxpython did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]

----snip ---

**Comment by swt2c** [comment]
@h00man you snipped the relevant parts of the output.  :(  When I saw it earlier via email, your error had nothing to do with attrdict.  Instead, you're missing some Linux package prerequisites needed to build wxPython.  See https://github.com/wxWidgets/Phoenix#id8.

**Comment by swt2c** [comment]
New release 4.2.1 has been made which removes attrdict as a requirement on Linux.
