### ISSUE TITLE
Specific error message vs SegFault?

### ISSUE THREAD

**Issue by N46AN** [wxWidgets/Phoenix#238]
**Basic Info:**
wxver - wxPython_Phoenix-3.0.3.dev2812+b3485d4-cp35-cp35m-linux_x86_64
pyver - Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] on linux
uname - Linux debian 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
os-release - Debian GNU/Linux 9 (stretch)

**Step to reproduce:**
Run the following minimal example with python 3.5 and wxPython_Phoenix-3.0.3
```
import wx

class MainFrame(wx.Frame):
	def __init__(self):
		wx.Frame.__init__(self) # Intentionally leave out the arguments
		pnl = wx.Panel(parent=self)

app = wx.App()
frame = MainFrame()
frame.Show(True)
app.MainLoop()
```

**What happened:**
```
$ py3 hello.py
Segmentation fault
```

**Expected result:**
It should return some specific infomation such as "Required argument not found":
```
$ py3 hello.py
Traceback (most recent call last):
  File "hello.py", line 10, in <module>
    frame = MainFrame()
  File "hello.py", line 6, in __init__
    wx.Frame.__init__(self)
  File "/usr/lib/pythonXXX/dist-packages/wx-XXXXXX/wx/_windows.py", line 580, in __init__
    _windows_.Frame_swiginit(self,_windows_.new_Frame(*args, **kwargs))
TypeError: Required argument 'parent' (pos 1) not found
```

-------------------------
**Note** that if the line "pnl = wx.Panel(parent=self)" is removed, the error message becomes:
```
Traceback (most recent call last):
  File "hello.py", line 11, in <module>
    frame.Show(True)
wx._core.wxAssertionError: C++ assertion "m_widget" failed at /home/ubuntu/wxPython_Phoenix-3.0.3.dev2812+b3485d4/ext/wxWidgets/src/gtk/toplevel.cpp(988) in Show(): invalid frame
```
Which is still too vague to be helpful.

Thanks!

**Comment by RobinD42** [comment]
> It should return some specific infomation such as "Required argument not found":

But it isn't required.  All widget types can be constructed with no args, which will basically create the C++/Python part of the object, but not the GUI part.  In order to create the GUI object in this case you must call the `Create` method, (wxWidgets tends to call this "2 phase create" or similar) and anything that needs to interact with the GUI object simply can not be done until after the `Create` method has been called.

The error you are seeing is due to the panel trying to use the GUI part of the parent object, but it hasn't been created yet. While it would be nice to have a better error reporting in cases like this, it will likely need to be done in the C++ layers and may be more effort than it is worth.

**Comment by RobinD42** [comment]
Also: https://wxpython.org/Phoenix/docs/html/MigrationGuide.html#phase-create

**Comment by N46AN** [comment]
Thanks for the detailed explanation. If we execute the above minimal example with python 2.7.13 and wxPython 3.0.2.0 gtk2 (classic), it would raise an "TypeError: Required argument 'parent' (pos 1) not found":

So I assume something has changed in wxPython Phoenix regarding this scenario?

Thanks!

------------------------

```
$ python2.7
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'3.0.2.0 gtk2 (classic)'
>>> 
$ python2.7 hello.py 
Traceback (most recent call last):
  File "hello.py", line 10, in <module>
    frame = MainFrame()
  File "hello.py", line 6, in __init__
    wx.Frame.__init__(self)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_windows.py", line 580, in __init__
    _windows_.Frame_swiginit(self,_windows_.new_Frame(*args, **kwargs))
TypeError: Required argument 'parent' (pos 1) not found
```

**Comment by RobinD42** [comment]
Yes. See the Migration Guide link above.  Since we now support wrapping overloaded methods there is no need to rename the default constructor. In Classic to create a frame where the GUI object hasn't yet been created you had to do `frm = wx.PreFrame()`, now it is just `frm = wx.Frame()` like it is in C++.

**Comment by N46AN** [comment]
Thanks very much for the detailed explanation and your continuous effort on this great project!
