### ISSUE TITLE
Python 3.12 distutils package has been removed

### ISSUE THREAD

**Issue by da-dada** [wxWidgets/Phoenix#2519]
**Operating system**:
**wxPython version 3.12**:          
**the demo doesn't run**:            

**Main.py of   wxPython-demo-4.2.1\demo line 59   from distutils.version import LooseVersion**:

<details>
  <summary>Code Example (click to expand)</summary>

```python
# Put code sample here
```
</details>

**Comment by DietmarSchwertberger** [comment]
A real stack backtrace would have been nicer to read, 'demo' does not have a line 59.
Or, you could have submitted a PR yourself...

Anyway:

Actually, distutils is not yet gone, it's now part of setuptools before it will eventually die.
The build tools for wxPython still seem to have many dependencies on distutils, which needs to be changed.
Due to this dependency, anyone who is building wxPython has setuptools/distutils installed and does not see this bug...

**Comment by da-dada** [comment]
in **wxPython-demo-4.2.1\demo** there is module **Main.py** which gets called at demo and here at line 59 happens to be `from distutils.version import LooseVersion` which dumps (your setuptools comment is true but the import machinery doesn't get it)

**Comment by Metallicow** [comment]
umm yea demo no line 59 or 42 either.... Thread extinguished.

**Comment by egoZentric** [comment]
> Anyway:
> 
> Actually, distutils is not yet gone, it's now part of setuptools before it will eventually die.....

Actually it has been long depriciated and i finaly gone with version 3.12 see https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated

So all of us with new installs fail here and so will all futer uses

Traceback (most recent call last):
  File "C:\Users\***\wxPython-demo-4.2.1\demo\demo.py", line 3, in <module>
    import Main
  File "C:\Users\***\wxPython-demo-4.2.1\demo\Main.py", line 59, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by egoZentric** [comment]
SOLVED.

https://github.com/wxWidgets/Phoenix/pull/2520

https://github.com/wxWidgets/Phoenix/commit/7e2c7d69c9a71c77b3fb2e0f3d55ccbc7eab6742

**Comment by Metallicow** [comment]
Ok, good buddy, let's make it clear...

I was the one that spent GOD-KNOWS how many hours porting the old classic
wxpython demo and numerous modules to work on wxPhoenix. ...having said
that most of what you see is a (WIPz) throughout the years. Some stuff
simply wasn't needed. Why, you ask...? Well simply because installing
python and wxpython was good enough(might add pywin32 and pillow).

A philosophy of 'Project Phoenix's was to eliminate CRUFT beyond classic
wxpython(was being built with swig instead of sip). Now that you have a
extraordinary sized glass of brew, take a sip, it is almost as refreshing
as getting a whole glass. Toast, cheers.

By the way, if you are interested in working on the framework, I have
already started a community ideas based one, tho it well.... NEEDs work
from more than a one man army... Get it. There used to be a wxUsers and
wxDev groups on mailing lists, ... Now basically there is forums type on
discuss.wxpython

I have gotten lots of praise for my 'BAIN' style working of the wxdemo
framework, but it is a hacked up mess.
... And yes I have it hosted on GitHub if you want to hack some more on it.

Thanks.

**Comment by da-dada** [comment]
I like sipping crafters..

**Comment by Metallicow** [comment]
Good response good buddy.
