### ISSUE TITLE
return in finally swallows exceptions.

### ISSUE THREAD

**Issue by iritkatriel** [wxWidgets/Phoenix#2630]
In https://github.com/wxWidgets/Phoenix/blob/82b1c7aa7ea28f9f142efcd3f31942b1011a5d6d/wx/lib/agw/flatmenu.py#L5364
there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body,  it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by komoto48g** [comment]
@swt2c, I commented #2373 and proposed `finally return`.
But it seems fine even if it doesn't return a bool value, as it can close without issues. If I understand correctly, this is because wx.lib.agw.flatmenu.FlatMenu is a subclass of `wx.PopupWindow`, not `wx.TopLevelWindow`.
So to keep the code healthy, I'd make a PR like this:
```
     def Destroy(self, *args, **kwargs):
        self.Clear()
        return super().Destroy(*args, **kwargs)
```
