### ISSUE TITLE
Issues with behavior of wx.dataview.TreeListCtrl

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#274]
1. The first issue is with the same item ID changing. For example

```python
            item= self.tree.GetSelection()
            item2 = self.tree.GetSelection()
            
            print(item==item2)  #same item yet different ID. returns false
            
```
The item ID changes.  Not sure if this is actually the expected behavior but if it is, then how would one compare items in a TreeListCtrl?

2. As I understand it, dataview.TreeListCtrl is ported from gizmos.TreeListCtrl

But some methods have not been included in dataview.TreeListCtrl. Also not sure if this is by design or not yet fully ported but is there any way of getting the previous item?

For example, some functionality I would like to achieve

```python
GetPrev(self, item), GetPrevChild(self, item, cookie), GetPrevExpanded(self, item)
GetPrevSibling(self, item), GetPrevVisible(self, item, fullRow)
 ```

-----

Which kind of ties into my first issue where I can't match item IDs correctly as a way of finding the previous item.

**Comment by RobinD42** [comment]
1. I assume based on your next question that this is a `dataview.TreeListItem`, not a `dataview.DataViewItem`... If that's the case then it looks like that class does not have an equality operator exposed, but I may be able to add one.  I'll check into it.

2. No, it isn't It's a new class which uses a  `DataViewControl` internally with a model that supports both hierarchical and tabular data. As such it has a different history and purpose, and so the API is accordingly different. I don't plan on porting over the gizmos library because the C++ code is not well maintained, but I would be open to having at least some of the classes there being ported to pure Python implementations if somebody cares to do it and submit a PR. (Yes, I'm dropping a hint.)

Take a look at the `dataview.TreeListCtrl` API docs, there are equivalents of at least some of those methods. If you need more then you can probably use `GetDataView` and dig into it that way.

**Comment by swprojects** [comment]
1. Correct, I was referring to dataview.TreeListItem

2. Ah I see. Hopefully someone takes that hint :) I would love to help but at the moment is probably suited for someone who isn't a relative newbie like myself. Though I do plan on learning how to make more useful/involved code contributions to projects (in general) in the future. Step by step I guess...
