### ISSUE TITLE
Redo support for Microsoft Visual C++ Compiler for Python 2.7

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#280]
@wettenhj, I've had to revert PR #255 as it seems to have caused the manifest to be left out of the DLL resources, at least for normal Visual Studio 2008 builds. See #275. If you can work out why it is doing that and how to avoid it then please submit another PR for it.

**Comment by wettenhj** [comment]
OK, thanks for letting me know.  I think the "import setuptools" changes are harmless - it's more likely to be the change to the Waf configuration (conf.env['NO_MSVC_DETECT'] = 1) which broke it.

It might be better to fix the MSVC++ For Python2.7 support in Waf instead of trying to use a workaround in wxPython's wscript.

It looks like wxPython currently uses Waf 1.7.15-p1: https://github.com/wxWidgets/Phoenix/blob/master/build.py#L86

Is "p1" an official patch to v1.7.15 released by the Waf maintainers?  Or was it built from a fork of the official Waf repository?

Are there any other factors I should be aware of influencing wxPython's choice of Waf version?

**Comment by RobinD42** [comment]
I think the p1 was an official patch release of waf.

In the past there was a bunch of monkey-patching and other code replacement going on that could make updating to a new version of waf a little painful, but it looks like all that is left in the current version  of `wscript` is the `my_check_python_headers` function. I don't remember exactly what the problem was that it solved, but if the problem isn't there any more in the new waf then that could be removed.

**Comment by mesalu** [comment]
@RobinD42 status of this issue?

**Comment by RobinD42** [comment]
Not sure. I don't think I've heard anything about using "Microsoft Visual C++ Compiler for Python 2.7" since the version of waf we're using has been updated, but it's probably okay to assume success until we hear otherwise. Closing.
