### ISSUE TITLE
TaskBarIcon doesn't show if no TaskBarIcon event is bound to a handler

### ISSUE THREAD

**Issue by swprojects** [wxWidgets/Phoenix#344]
Windows 10  64-bit
python 3.5

Spent a bit of time wondering why my tray icon wasn't showing...but it seems to only show when a event is bound.

```python

import wx
import wx.adv

class Tray(wx.adv.TaskBarIcon):

    def __init__(self):
        super(wx.adv.TaskBarIcon, self).__init__()
        bmp = wx.ArtProvider.GetBitmap(wx.ART_TICK_MARK)
        self.SetIcon(wx.Icon(bmp))

        ##### uncomment/comment binding below #####
        self.Bind(wx.adv.EVT_TASKBAR_LEFT_DOWN, self.OnTray)

    def OnTray(self, event):
        print(" event ..")
        
app = wx.App()
Tray()
app.MainLoop()
```

**Comment by RobinD42** [comment]
Since the taskbar icon is not owned by another UI element, and is not tracked internally like frames, then it is deallocated/destroyed when the reference count reaches zero like most Python objects.  Binding an event handler adds an internal reference to the object, via the bound method.  If you keep a reference to the taskbar icon yourself then that will keep it from being removed. Something simple like this would work: `tbi = Tray()`
