### ISSUE TITLE
"Cannot find vcvarsall.bat" when installing via PIP on Windows

### ISSUE THREAD

**Issue by hyphz** [wxWidgets/Phoenix#364]
This error appears whenever I try to install via PIP on Windows, even when Visual Studio is installed and vcvarsall.bat is on the PATH.

**Comment by wettenhj** [comment]
Are you trying to install a binary wheel?  Or are you trying to build from source?

If you are trying to build from source, you should specify the Visual Studio version you are using and the Python version you are using.  And the path to vcvarsall.bat might be relevant - from Command Prompt, you can run "where vcvarsall.bat".

**Comment by RobinD42** [comment]
And also which version of Python you are using (and being used for running pip) and where that Python came from if it is not a stock build from python.org.

**Comment by obdevel** [comment]
The problem manifests itself with more recent versions of Visual Studio (e.g. VS 2017), as the compiler version has been incremented to 10, whilst distutils seems to expect <= 9.

```C:\Users\xxx\wx\Phoenix>python setup.py build
running build
WARNING: Building this way assumes that all generated files have been
generated already.  If that is not the case then use build.py directly
to generate the source and perform the build stage.  You can use
--skip-build with the bdist_* or install commands to avoid this
message and the wxWidgets and Phoenix build steps in the future.

"C:\Python27\python.exe" -u build.py build
Will build using: "C:\Python27\python.exe"
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Python's architecture is 64bit
cfg.VERSION: 4.0.0a3

Running command: build
Running command: build_wx
Command '"C:\Python27\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
Finished command: build_wx (0.484s)
Finished command: build (0.484s)
Command '"C:\Python27\python.exe" -u build.py build' failed with exit code 1.```

**Comment by RobinD42** [comment]
For Python 2.7 you need to use either Visual Studio 2008 or "Visual Studio for Python 2.7" from https://www.microsoft.com/en-us/download/details.aspx?id=44266  For the latter you will probably also need a little tweaking on the build scripts to build wxPython. There was a PR here that made the changes but it had to be revered because it caused problems when using VS 2008. Look through the closed PRs and you should be able to find it.

IIRC, VS 2017 does provide compatibility modes for building with older versions of the compiler (or as if the build was done with the older version). I've yet to try it myself, but I don't think it goes back that far.

**Comment by mesalu** [comment]
Closing as old and inactive. 
If you still require guidance getting Phoenix to build from source on Windows please reopen this issue.

**Comment by leonardder** [comment]
I have Python 3.7 with Visual Studio 2019 installed and am facing the same issue. Wouldn't it be possible to stop using distutils and use setuptools instead? This seems to be the recommended way now.

**Comment by RobinD42** [comment]
We do use setuptools, but just as one layer. We also use waf to run the actual build, mainly because when you've got around 900 source modules to compile, plain distutils and setuptools are painfully slow. They can't handle more than one simultaneous compile, and typically will need a full rebuild when minor things change instead of only rebuilding the modules that need it.

The waf tool uses similar code as setuptools does for locating the compiler commands to be used, but I've not tried with VS 2019 yet. It may be that waf needs to be updated for that to work. You can try out a different version of waf by setting the WAF environment variable to be the path to the waf executable you want to try.

**Comment by leonardder** [comment]
> Wouldn't it be possible to stop using distutils and use setuptools instead?

I should express myself clearer here. distutils has a very limited way of looking up the compiler. IN the checkCompiler function in build.py ,if we import setuptools before distutils, setuptools will patch distutils so that it should at least be able to use the Visual Studio 2017 build tools instead and/or gives more detailed errors about what's wrong about the setup.
