### ISSUE TITLE
Activate travis-ci.org builds

### ISSUE THREAD

**Issue by krichter722** [wxWidgets/Phoenix#386]
It'd be nice if one could track the build success of commits at https://travis-ci.org/wxWidgets/Phoenix for every commit instead of just pull requests.

**Comment by mesalu** [comment]
We've since migrated to CircleCI.

Every commit will be tested as part of a pull request.
Running CI on every commit ever will be unrealistic for public-use CI.

If you'd like to test your own commits prior to opening a PR I suggest opening an CI account for your own fork and configuring it accordingly
