### ISSUE TITLE
missing wx.adv.TreeListCtrl.SetItemHasChildren

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#388]
it is present in Classic and other tree controls in phoenix have this method (win10, python3.5)

Marco

**Comment by RobinD42** [comment]
`wx.adv.TreeListCtrl` is not the same class as the `wx.gizmos.TreeListCtrl` class in Classic. The gizmos classes have not been ported to Phoenix, and probably won't be since the C++ code doesn't seem to be maintained. (Although I would welcome versions of some of those classes ported to pure Python.)

The C++ class for `wx.adv.TreeListCtrl` does not have a `SetItemHasChildren` method. I think the intent there is that if you need something more than a simple tree+list ctrl that you should use `DataViewCtrl` instead.
