### ISSUE TITLE
NullColour always compares as True

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#404]
Comparing anything to wx.NullColour always returns True, but comparing to identical colour returns False.

```
>>> wx.NullColour
wx.Colour(-1, -1, -1, 255)

>>> "X"==wx.NullColour
True

>>> wx.Colour(-1,-1,-1,255)==wx.NullColour
False

>>> "X"==wx.Colour(None)
True

>>> "X"==wx.Colour(-1,-1,-1,255)
False

>>> sys.version
'3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)]'
>>> wx.version()
'4.0.0a4.dev3150+888e0ef msw (phoenix)'
```

**Comment by DietmarSchwertberger** [comment]
Classic has the same behaviour already, so it might be OK not to fix.

**Comment by RobinD42** [comment]
It can be a little unexpected or confusing, but the current behavior is as it is intended to be. Here are some missing details:

```
>>> wx.NullColour
wx.Colour(-1, -1, -1, 255)
```

There is one more component of the wx.Colour object not shown there, a flag indicating if the colour object has been initialized or not. In the case of `wx.NullColour` it is `False`. (You can check if a colour object has been initialized using `IsOk`.)

```
>>> wx.Colour(-1,-1,-1,255)==wx.NullColour
False
```

This evaluates to `False` because the first colour object has been initialized so the flag is `True`. It doesn't distinguish between  valid and invalid, just initialized and not initialized.  On the other hand:

```
>>> wx.Colour() == wx.NullColour
True
```

That is comparing with an uninitialized colour, so it evaluates to `True`.

```
>>> "X"==wx.NullColour
True
```

wxPython attempts to automatically convert strings (either colour names or #RRGGBB formatted strings) to `wx.Colour` objects. Since there is no colour named "X" then it results in a `wx.Colour()` which compares equal to `wx.NullColour`.

The rest of your cases all fall into one or more of the above explanations.
