### ISSUE TITLE
Hang when destroying wxWindow

### ISSUE THREAD

**Issue by ChrisRedacted** [wxWidgets/Phoenix#405]
In the sip_corewxWindow.cpp, in function:

static PyObject *meth_wxWindow_Destroy(PyObject *sipSelf, PyObject *sipArgs)

There is a part that says:

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp-> ::wxWindow::Destroy() : sipCpp->Destroy());
            Py_END_ALLOW_THREADS

I think wrapping that function call with the "ALLOW_THREADS" macros can cause an app to hang when a wxWindow is being destroyed. The way that can happen is if you register a wxEventHandler and bind a function to the Destroy message like so:

     self.Bind( wx.EVT_WINDOW_DESTROY, self._on_destroy )

Then, in that on_destroy function, you can call some Python function that is also wrapped with "ALLOW_THREADS" macros. In our case, it was the "GetChildren" method of a window. 

Recursively calling the ALLOW_THREADS macros is apparently considered "not good" by Python code, Wherein it says in ceval.h above the definition of those macros: 

   WARNING: NEVER NEST CALLS TO Py_BEGIN_ALLOW_THREADS AND
   Py_END_ALLOW_THREADS!!!

I have verified that after I delete the wrapping ALLOW_THREADS macros from the Destroy call, our application no longer hangs trying to obtain the GIL. But sadly, I've only figured out how to modify the SIP-generated .cpp file. I tried for some time, but I simply cannot find the "source" code for this sip_corewxWindow.cpp.

So I have two questions:
1) How do I modify the "source" file for that SIP-generated sip_corewxWindow.cpp.
2) Does this seem like we should pull this fix to mainline wxPython? I'm thinking that it's anyway dangerous to try to do multithreading while destroying windows, and that destroying windows is not something that takes a long time, unless you're running some really expensive Python code, in which case, you're probably running code that's not multithreading safe anyway.

Thanks!

**Comment by ChrisRedacted** [comment]
I should say I'm on WX Python 4.0.0a3
OS: Win10
Python version: 3.5

**Comment by mmmmichael** [comment]
The Py_BEGIN_ALLOW_THREADS is correct -> your crash must have a different reason.
The normal rule is: C++ called from Python is wrapped by Py_BEGIN/END_ALLOW_THREADS releasing the GIL, and Python called from C++ (like calling your _on_destroy) requires acquiring the GIL (again). Breaking this rule would open a can of worms which cannot be controlled. The warning you quoted is only about nesting Py_BEGIN_ALLOW_THREADS without releasing the GIL in-between. Alternating nesting of Py_BEGIN_ALLOW_THREADS with GIL-acquisition is fine and very important.

**Comment by RobinD42** [comment]
@mmmmichael is correct. When your event handler is called it will first reacquire the GIL and so when your handler calls `GetChildren` there will be another `Py_BEGIN/END_ALLOW_THREADS`  wrapping that call.  

Although you are correct that destroying windows does not take a lot of time, the issue is that we are using a SIP feature to *always* wrap the wrapped C++ method calls in `Py_BEGIN/END_ALLOW_THREADS` (just like we did in wxPython Classic with SWIG). Picking and choosing which should release the GIL and which shouldn't would just lead to way too many cases where the wong decision was made, or somebody simply forgot about it.  Doing it for all wrappers and then being careful about always reacquiring it is a much better approach.

Now, to address your problem... Are you calling the `GetChildren` method of the window that is being destroyed?  If so, then that is where I would lay the blame.  It is likely too late to safely do *anything* to that window in that event handler. I would only use it for notifying the parent or some other part of the application that the window is being destroyed, and whatever you are doing with the `GetChildren` find a way to do it before the window is destroyed and the  `wx.EVT_WINDOW_DESTROY` is sent.

**Comment by ChrisRedacted** [comment]
Thanks @mmmmichael and @RobinD42! Good to know that this is function wrapping is done automatically, and that this was apparently done in Classic. This is oddly a new problem we're encountering upon upgrading from Classic to Phoenix, even though this particular code was not changed between versions. 

After reading @mmmmichael's response, I was stepping through this again, investigating how GIL acquisition/release was working. It's hard to track because it's grabbed and released super frequently. But while I was looking at this again, I noticed that we are (for some mysterious reason) calling Destroy on a pane at the time when its containing window is being closed. It appears that I can also remove this Destroy pane call, and that also appears to eliminate the hang, without requiring a change to WX code and no negative impact that I can see. Thanks again for the explanations!
