### ISSUE TITLE
Custom wxPython WebView handler registration crashes due to wrong sip parameter types

### ISSUE THREAD

**Issue by mmmmichael** [wxWidgets/Phoenix#406]
wxPython 4.0.0a3:

Registering a custom handler to the wxPython WebView crashes due to wrong SIP parameter types.

In the file sip/cpp/sip_corewxFSFile.cpp in the function init_type_wxFSFile in the call of sipParseKwdArgs the parameter "J0J1J1J1J1" should be "J2J1J1J1J1".

And in the file sip/cpp/sip_html2cmodule.cpp in the function sipVH__html2_0 in the call of sipParseResultEx the parameter "H0" should be "H2".

I'm not familiar with SIP, so I'm not sure how to make these changes in the SIP configuration, but I assume someone knowing this stuff can do this easily. :-)

See also http://trac.wxwidgets.org/ticket/17892.

**Comment by swt2c** [comment]
Do you have a self-contained code sample that reproduces the problem?

**Comment by RobinD42** [comment]
Thanks for digging that far into the problem. Those flags in the format strings control ownership transfers of the C++ objects to or from their Python proxy objects. They are specified in SIP code with some annotations like /Transfer/ and etc., but since we also generate our SIP code then it is specified with some simple property assignments in the appropriate `etg/foo.py` I'm putting together at PR for that now which will be linked here when it's ready.

P.S. Next time, in addition to a code sample, all you'll really need to say is something like wx.Foo.Bar does not appear to be handling ownership transfers correctly.  :-)

**Comment by swt2c** [comment]
Thanks Robin, I was trying to reverse engineer what those flags meant.  :-)

**Comment by mmmmichael** [comment]
Great!
Obviously you built a quite smart system here.
Thanks for all the great work over all the years!
