### ISSUE TITLE
segfault in DataViewListCtrl.SetValue when using a virtual model

### ISSUE THREAD

**Issue by acollange** [wxWidgets/Phoenix#418]
Hello,

When a `DataViewVirtualListModel `is associated to a `DataViewListCtrl`, calling `DataViewListCtrl.SetValue` cause a segmentation fault.

See the test case attached to reproduce the issue.
I was able to reproduce the crash on :
  - GTK / Python3.6.1 (x64) / Phoenix 4.0.0a3
  - Windows / Python 3.6.1 (x64) / Phoenix 4.0.0a3

The same code on the following platform works fine :
  - GTK / Python 2.7.12 (x64) / wxPython 3.0.1.1
  - Windows / Python 2.7.12 / wxPython 3.0.1.1

[dvlist.py.txt](https://github.com/wxWidgets/Phoenix/files/1106031/dvlist.py.txt)

**Comment by RobinD42** [comment]
To be honest I'm surprised it is not crashing with Classic too. Looking at the `DataViewListCtrl` code there are some things that make me think it was not intended to be used with models other than `DataViewListStore`.

Instead you should use`DataViewCtrl` and associate your derived `DataViewVirtualListModel` with that. Then I would just modify the data directly in the model instead of going through the control to do it. Just be sure to call the methods that will cause the model to notify the view that something has changed.  

If you would rather have a method on the control like `SetValue` then adding something like this in a derived class should work:

```
    def SetValue(self, value, row, col):
        self.GetModel().SetValueByRow(value, row, col)
        self.GetModel().RowValueChanged(row, col)
```
