### ISSUE TITLE
Build succeeded, import failed

### ISSUE THREAD

**Issue by Korijn** [wxWidgets/Phoenix#423]
We're working on a conda package for wxPython. The windows version is done (yay!) but the Linux and OS X version are still a work in progress. The linux build has passed, however, we still get some errors when trying to `import wx`. Specifically, this happens:

```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/wxpython_1498486398574/_t_env
+ /feedstock_root/build_artefacts/wxpython_1498486398574/_t_env/bin/python -s /feedstock_root/build_artefacts/wxpython_1498486398574/test_tmp/run_test.py
import: 'wx'
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/wxpython_1498486398574/test_tmp/run_test.py", line 2, in <module>
    import wx
  File "/feedstock_root/build_artefacts/wxpython_1498486398574/_t_env/lib/python2.7/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/feedstock_root/build_artefacts/wxpython_1498486398574/_t_env/lib/python2.7/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libwx_gtk2u_core-3.0.so.0: cannot open shared object file: No such file or directory
TESTS FAILED: wxpython-4.0.0a2-py27_0.tar.bz2
```

I found one of y[our posts on SO regarding this problem](https://stackoverflow.com/a/31928092/552379), and I tried your advice (using `ldd`) to see what the problem is, and it yields this result:

`libwx_baseu-3.0.so.0 => not found`

Would you be able to tell us what that means?

**Comment by RobinD42** [comment]
Did you try setting the `LD_LIBRARY_PATH` environment variable as described there?

Do you know if anything in the anaconda-specific parts of the build messes with the rpath settings in the extension modules? Phoenix's build sets the rpath in the wxPython extension modules by default such that it will look in the same folder for shared libraries. That is how I'm able to bundle the wxWidgets libs in the wxPython package and enable it to be easily relocatable. 

If anaconda is setting its own rpath -- to enable searching for things first in the anaconda prefix, for example -- then that could be the source of the problem.  If so, and if it can't be turned off for the wx libs, then a possible fix would be to use the `build.py` options to not build wxWidgets that way or bundle it into the wxPython package folder. 

It's been a long while since I've tested these things, but I expect that they should still work. You'll probably want to run the wx build and install first, `build_wx` and `install_wx`, probably with `--no_magic` and `--prefix`, followed by the commands to build and install just wxPython, again with `--no_magic` and `--prefix` and also `--use_syswx`.

**Comment by Korijn** [comment]
Anaconda actually does a ton of magic to binaries, rewriting paths and whatnot. So I suspect that its magic might be clashing with that of wxWidgets.

If I understand correctly, the command I will need is then `python build.py build_wx install_wx --no_magic build_py install_py --no_magic --use_syswx`. I don't think I'll need --prefix, unless `build.py` expects it, since Anaconda handles all that automatically already. Would you agree with my assessment, or is my command wrong?

**Comment by RobinD42** [comment]
It may work okay, but I would try it first as 2 separate commands, `python build.py build_wx install_wx --no_magic` and `python build.py build_py install_py --no_magic --use_syswx`

**Comment by RobinD42** [comment]
> It's really only libwx_baseu-3.0.so.0 that is not being found,

Which could still be due to anaconda's magic.  IIRC that lib will only be loaded indirectly by the wxPython extensions, via the other wx shared libs that use it.

**Comment by RobinD42** [comment]
@Korijn have you made any progress on this?  If you've solved it please give the details here in case somebody else runs into the issue.

**Comment by Korijn** [comment]
almost! we need a little bit more time.

**Comment by RobinD42** [comment]
Any updates?

**Comment by Korijn** [comment]
You can follow our progress here:

https://github.com/conda-forge/wxpython-feedstock/pull/7

We're still having issues...

**Comment by Korijn** [comment]
https://github.com/conda-forge/wxpython-feedstock/pull/9

https://github.com/conda-forge/wxpython-feedstock/pull/10

We got it to work. See the linked PRs for all the details.

Thanks Robin!
