### ISSUE TITLE
wx.DLG_UNIT returns wx.Point instead of wx.Size when argument is just a tuple

### ISSUE THREAD

**Issue by DietmarSchwertberger** [wxWidgets/Phoenix#426]
Classic:
```
>>> wx.DLG_SZE(self.widget, (10,10))
wx.Size(15, 16)
```

Phoenix:
```
>>> wx.DLG_SZE(self.widget, (10,10))
D:\Python\Sources35\wxglade_dev\edit_windows.py:1: wxPyDeprecationWarning: Call to deprecated item. Use DLG_UNIT instead.
  """
wx.Point(15, 16)
wx.DLG_UNIT(self.widget, (10,10))
wx.Point(15, 16)
```

When calling with a wx.Size the returned type is correct:
```
>>> wx.DLG_SZE(self._0_N_N_copy_1, wx.Size(100, 21))
wx.Size(150, 34)
```

Usually, the return value is used as argument to e.g. SetMinSize, which does accept tuples and wx.Size, but not wx.Point.

**Comment by mesalu** [comment]
DLG_UNIT is a convenience wrapper for an overloaded function: wx.Window.ConvertDialogToPixels
which can take a wxPoint and return a wxPoint or a wxSize and return a wxSize. See: https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.ConvertDialogToPixels

I assume that DLG_SIZE was a Classic-modification to force particular behavior out of ConvertDialogToPixels, because I don't even have it available in my Phoenix installation. Though I can't say for sure... @RobinD42  would be able to address that.

```Python
>>> import wx
>>> wx.DLG_SIZE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wx' has no attribute 'DLG_SIZE'
>>> wx.PlatformInfo
('__WXMSW__', 'wxMSW', 'unicode', 'unicode-wchar', 'wx-assertions-on', 'phoenix'
, 'wxWidgets 3.0.3')
```

In Phoenix the first matching call to the wrapped ConvertDialogToPixels will be used, which in this case will be for wxPoint (as both size and point have automatic conversions from tuples).

So barring intervention from @RobinD42, this is desired behavior. 

Sam

**Comment by RobinD42** [comment]
Perhaps we should change `wx.DLG_UNIT` to convert back to a tuple if a tuple was passed in... Since `wx.Point` and `wx.Size` implement some sequence operators then then this would work:

```python
    pix = win.ConvertDialogToPixels(dlg_unit)
    if whatever:
        pix = tuple(pix)
    return pix
```

Lists and numpy arrays are also allowed to implicitly convert to `wx.Point` and `wx.Size`, but maybe just converting to tuple in those cases too would be okay, in order to not complexify it too much.

**Comment by DietmarSchwertberger** [comment]
I would prefer this solution over the current behaviour.
This would be elegant and backward compatible at the same time.

I can live with the current implementation as well. For the time being, I have adjusted the code generation in wxGlade to add a wx.Size( ) around calls of DLG_SIZE / DLG_UNIT.
