### ISSUE TITLE
wx.CallLater not always calling function

### ISSUE THREAD

**Issue by kg-2** [wxWidgets/Phoenix#457]
Operating system: windows 10 64 bit

wxPython version: 4.0.0.b1

Stock or custom build: stock

Python version: 3.6.2

Stock or custom build: stock

Description of the problem:
I've noticed on 2 of my applications that wx.CallLater will sometimes never call the function.  There's no error and its hard to reproduce reliably.  I've tried for quite a while to create some minimum code that reliably recreates the problem, but haven't had much luck so far.

**Comment by RobinD42** [comment]
Is it possible that the UI thread of the application is extremely busy? The call afters are handled by adding a new event to the app's pending event queue, which are handled about the same as idle events. IOW, they will not be processed until the main event queue becomes empty.

**Comment by kg-2** [comment]
It might have something to do with that, I have noticed it more when the program is first starting up, but they never get called, even after everything is idle.

**Comment by ricpol** [comment]
Are we talking about wx.CallAfter or wx.CallLater here? Because wx.CallAfter performs a wx.PostEvent just like Robin said... and it would be surprising to see it failing. 
But a wx.CallLater is just a timer, and it could fail for a number of reasons... maybe the timer just stopped, or never got started, or got destroyed somehow...

**Comment by kg-2** [comment]
It's CallLater

**Comment by RobinD42** [comment]
Oops, sorry. I misread the title.  `wx.CallLater` is basically just a class derived from `wx.Timer` and timer events are also a lower priority so they could be affected by a busy main thread or blocked event loop in a similar way. What are the delay times you are giving to the `wx.CallLaters`? If they are very small and there are lots of them then it's possible the system is dropping some of them, although I don't remember details about that. However, there may be a better way to do what you need in those cases.

**Comment by kg-2** [comment]
The delay times are between 50-150 millis, with some concurrent calls.  There are other ways I can implement these delays via poll methods etc. I just wasn't aware of the potential that they wouldn't be called.

**Comment by RobinD42** [comment]
50-150 should be fine, unless the main thread is very busy or the event queue is saturated.

**Comment by kg-2** [comment]
That's very possible. I'm catching EVT_MOTION to update the position of a popup window.

**Comment by pauldmccarthy** [comment]
I have recently encountered similar behaviour, and I think it is actually due
to some invalid assumptions made in the `wx.CallLater` implementation.


`CallLater` uses a circular reference to try to prevent itself from being
garbage-collected, and thus allow callers to use it without retaining a
reference to it.


But this is a *very* implementation-specific assumption which does not hold at
all for python 3.x, due to improvements in the garbage collector.


The following test case demonstrates the problem. It runs fine under python
2.7 works (i.e. the `function` gets called periodically). But when it is run
under python 3.x, the ``MyCallLater`` object gets deleted before its target
`function` is called. I ran this against wxpython 4.0.0b2.


```python
#!/usr/bin/env python

import wx
import gc

class MyCallLater(wx.CallLater):
    def __del__(self):
        print('MyCallLater.__del__ called!')

def function():
    print('function called')
    MyCallLater(1000, function)
    gc.collect()

app   = wx.App()
frame = wx.Frame(None)

frame.Show()

MyCallLater(1000, function)

app.MainLoop()
```

I'm not sure how this bug can be resolved - as far as I see it, something is
going to need to hold a reference to the `CallLater` object to ensure that 
it doesn't get GC'd.

**Comment by mesalu** [comment]
> Changed in version 3.4: Following PEP 442, objects with a __del__() method don’t end up in gc.garbage anymore.

**Comment by pauldmccarthy** [comment]
Thanks @mesalu and @RobinD42 for the fast work!
