### ISSUE TITLE
Timer to set local time raise wxAssertionError???

### ISSUE THREAD

**Issue by jekoie** [wxWidgets/Phoenix#494]
**when is use wxpython 3.0 version no error raised, but now i use wxpython4.0.0.b1 it raise wxAssertionError!! Below is sample code**
```
      self.timer = wx.Timer(self)
      self.timer.Start(1000)
      self.Bind(wx.EVT_TIMER, self.OnTimer, self.timer)

    def OnTimer(self, evt):
        self.time_text.SetLabel( arrow.now().format('YYYY-MM-DD HH:mm:ss') )
```

> Error message see blow:
> Traceback (most recent call last):
>   File "D:/AutoTest/main.py", line 558, in OnTimer
>     self.time_text.SetLabel( arrow.now().format('YYYY-MM-DD HH:mm:ss') )
>   File "C:\Python27\lib\site-packages\arrow\api.py", line 40, in now
>     return _factory.now(tz)
>   File "C:\Python27\lib\site-packages\arrow\factory.py", line 250, in now
>     tz = dateutil_tz.tzlocal()
>   File "C:\Python27\lib\site-packages\dateutil\tz\tz.py", line 165, in __init__
>     self._std_offset = datetime.timedelta(seconds=-time.timezone)
> wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\common\filefn.cpp(1691) in wxParseCommonDialogsFilter(): missing '|' in the wildcard string!

**Comment by swt2c** [comment]
That's not enough code to reproduce the problem.  Please provide a runnable code sample that reproduces the problem.

**Comment by RobinD42** [comment]
Since it seems to be related to `wx.FileDialog` it's likely that the problem is in another event handler, but the timer event happened while that one was still in progress (probably in the `ShowModal`) and so it was the first one to have an opportunity to raise the exception for the assertion error. Double check things where you are using a file dialog. 

If you still can't solve the problem then whittle it down to a small-as-possible runnable sample that demonstrates the problem and post it here.

**Comment by jekoie** [comment]
I had wirte the simple script, try to reproduce the problem, but the script run well and not promble raise.
so i had post my script in https://github.com/jekoie/wxPython-AutoTest/blob/master/main.py ;
when a  filedialog opened  in line:1534 and then the issue raise  in  line:562
