### ISSUE TITLE
The wx.App object must be created first!

### ISSUE THREAD

**Issue by Bjoux2** [wxWidgets/Phoenix#556]
After installed wxPython, i run the 'hello world' example from [https://wxpython.org/pages/overview/#hello-world](url). in Jupyter Notebook.

```
# First things, first. Import the wxPython package.
import wx

# Next, create an application object.
app = wx.App()

# Then a frame.
frm = wx.Frame(None, title="Hello World")

# Show it.
frm.Show()

# Start the event loop.
app.MainLoop()
```

I got this error:

```
PyNoAppError                              Traceback (most recent call last)
<ipython-input-29-5af94fb54276> in <module>()
      6 
      7 # Then a frame.
----> 8 frm = wx.Frame(None, title="Hello World")
      9 
     10 # Show it.

PyNoAppError: The wx.App object must be created first!
```

**Comment by RobinD42** [comment]
Platform? wxPython version? Python version?

Did it work the first time and then fail after that?  (That is what happened for me.) Since Jupyter Notebook runs each python cell in the same python process you are running into an issue related to the nature of the `wx.App` object. It is expected that there is only one of them per process and so using wxPython in an interactive REPL environment doesn't work very well typically.

Try saving the code in a file and then run that file with the python executable from the command line. Alternatively, you can restart the Jupyter kernel between each run of a wxPython cell which has a `wx.App` and `MainLoop`.  You may also have some luck if you do `del app` after the return from `MainLoop`.

**Comment by DietmarSchwertberger** [comment]
I would not expect that running a GUI framework from within Jupyter will result in anything useful.
I have never used Jupyter, but from their homepage: "The Jupyter Notebook is an open-source web application..."
Running wxPython in a web application sounds adventurous....

Even if you use a wx based notebook system, I don't see what the purpose of this approach would be.

**Comment by RobinD42** [comment]
@DietmarSchwertberger, basically you can think of the Notebook as a stand-alone GUI front-end to a python instance running in another process. More like a souped-up IDE, interactive research environment, or learning environment, NOT the typical web-based application. From wxPython's perspective, you can think of it as analogous to running code in stock Python's interactive interpreter.  So, IOW, it should work, but I agree that it is not the best way to work with wxPython.

**Comment by segidev** [comment]
@Bjoux2 
You can fix this problem by putting the app into a separate cell and run it only once.

Like that: 
![image](https://user-images.githubusercontent.com/28906187/34957801-5f2d1a96-fa2f-11e7-9fb2-903c2bc595a3.png)


Run the top cell and then run the rest from now on. Worst case if you accidentaly run the first cell restart the kernel as metnioned :)

**Comment by mesalu** [comment]
Closing. Old and inactive.
A solution has been posted. If the provided solution does not solve your problem please reopen with updated information.
