### ISSUE TITLE
AttributeError: 'TreeListCtrl' object has no attribute 'SetItemTextColour'

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#565]
**Operating system**: Windows 10
**wxPython version**: 4.0.0b1
**Stock or custom build**: Stock
**Python version**: 3.6
**Stock or custom build**: Stock

**Description of the problem**:

`wx.dataview.TreeListCtrl.SetItemTextColour` no longer exists (from `wx.gizmos` in Classic). Removal of this is not mentioned in the migration guide.

Unfortunately I can't get a barebones working example up and running right now (and it's proved difficult to extract it from the application that I maintain) :/

**Comment by RobinD42** [comment]
`wx.dataview.TreeListCtrl` is not the same class as `wx.gizmos.TreeListCtrl` and is not intended to be a replacement. They have different origins and slightly different purposes. The gizmos module has not been ported to Phoenix yet, and since that C++ code has not been maintained for a long time I would rather that it be ported to Python code instead of wrapping the C++ version, but unfortunately that just hasn't happened yet. (PRs are welcome.)

In the meantime you may want to give `wx.lib.agw.hypertreelist` a try.

**Comment by blitzmann** [comment]
> In the meantime you may want to give wx.lib.agw.hypertreelist a try.

Thanks a bunch, will try this out :)

**Comment by infinity77** [comment]
@swt2c : I believe this can be closed: functionality is provided in HyperTreeList (automagically from wx.gizmos)
