### ISSUE TITLE
Pylint not detecting any wx objects/members

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/Phoenix#566]
Microsoft Windows [Version 10.0.15063]
wxpython-4.0.0b2 installed with pip from whl
Python 3.6.3 both 32 and 64 bit

First seen using Python 3.6.1 in a virtualenv but attached log was created from a clean install of Python 3.6.3 in a virtual Windows 10 machine with pylint checking a randomly selected small file (staticbox.py) from the demo.

[phoenix-pylint.log](https://github.com/wxWidgets/Phoenix/files/1368875/phoenix-pylint.log)

**Comment by RobinD42** [comment]
I'm not super familiar with PyLint, but my understanding is that it is a static python code analyzer, and that it doesn't actually import the packages/modules to look at the class objects and etc. in the runtime namespace. If that is the case then it is true, there is no `wx.Panel` defined in Python code, it is actually coming from the `wx._core` extension module.

Can PyLint be told to look in the corresponding `.pyi` files instead of the `.py` files? That is the standard-ish way to give more info about what is coming from the extension modules.

**Comment by david-hughes** [comment]
I couldn't find a way of including .pyi files but adding the following into the relevant **.pylintrc** file suppresses the errors for the named modules:

\# E1101: Module 'wx' has no 'xxxxx' member
\# E1101: Module 'win32api' has no 'xxxxx' member
\# E1101: Module 'win32file' has no 'xxxxx' member
\# E1101: Module 'win32process' has no 'xxxxx' member
 
generated-members = wx.\*, win32*.*

Unfortunately this also suppresses errors caused by typos in wx member names - but one assumes the programs are also going to be tested ;-)

**Comment by udifuchs** [comment]
You need to add the '--extension-pkg-whitelist=wx' option to pylint to mark that the wx module can be actively loaded.

**Comment by david-hughes** [comment]
extension-pkg-whitelist = wx, win32api, win32file, win32process

works fine for me in my .pylintrc file and genuinely mis-typed object names are picked up correctly, thanks.
