### ISSUE TITLE
 4.0b2 wxPythonDemo DVC_CustomRenderer  editing doesnt work

### ISSUE THREAD

**Issue by ravenboy** [wxWidgets/Phoenix#596]
**Operating system**: Mac OSX 10.12.6
**wxPython version**: 4.0b2
**Stock or custom build**: stock
**Python version**: Python 3.6.2
**Stock or custom build**:stock

**Description of the problem**:
if you run this demo on Mac OSX 10.12.6 when you select a cell and the editing control appears
if doesnt contain the value of the cell, instead it contains this text "<wxCustoRendererObject: 0x1006101d107> . if you then move off that cell without editing it, the cells value is set to the bad text that was in the control. 

additionally:
1.  the custom renderer in this demo doesnt actually create the control for editing. the CreateEditorCtrl member never gets called. this is evident in the log output. So using a custom renderer for 4.0b2 doesn;t  actually allow creation of....  custom EDITOR controls.

2. copy and paste (using keyboard shortcuts  to the editor control  does not work. this functionality works if you run the demo on WIndows 10 (using same wxPyton and same Python versions)

In a stand alone py app i tried to create a custom renderer and had the same exact result

on Windows 10 this demo functions properly with respect to the problems enumerated above for Mac OSX 10.12.6 - you can see that CreateEditorCtrl is logged in the log,  and copy and paste functions properly.

**Comment by RobinD42** [comment]
I've dug into this before and was not able to find a solution. I'll give it another try.

**Comment by RobinD42** [comment]
Ok, it turns out this isn't actually a wxPython problem. The native widget used for the C++ DVC doesn't support custom editors, and there seems to be a problem with the implementation of the custom renderer's interface with the edit control.  

http://trac.wxwidgets.org/ticket/16866

It sounds like there are also similar issues with the native widget used on GTK.

The C++ DVC sample doesn't make the cells with a custom renderer editable, just activatable. I'll do something similar in our demo, plus add some info that makes it more obvious that it's known that editor controls are not expected to work with custom renderers except on Windows.

What would be really nice is if there was an option to use the generic C++ DataViewControl on all platforms. Maybe in 4.1...
