### ISSUE TITLE
wx._core.wxAssertionError when closing window with grid and cell editors

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/Phoenix#627]
**Windows 10 and OS X 10.12.6**
**wxPython version is 4.0.0rc1.dev3502+4535d53 msw (phoenix)**
**Stock build**
**Python is version 3.6.1**
**Stock build**

[flatnotebook-exception-win32.txt](https://github.com/wxWidgets/Phoenix/files/1495785/flatnotebook-exception-win32.txt)
[flatnotebook-exception-osx.txt](https://github.com/wxWidgets/Phoenix/files/1495786/flatnotebook-exception-osx.txt)

The exception occurs when closing a page containing a grid with GridCellEditors. Most of the editors are customised, derived from a class based on the example in _wxPython in Action_ and containing a modification to pop the corresponding event handler that's pushed when each instance is created.

    def Create(self, parent, nid, evtHandler):
        """
        Called to create the control, which must derive from wx.Control.
        """
        self._tc = wx.TextCtrl(parent, nid, "", style=wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB)
        self._tc.SetInsertionPoint(0)
        self.SetControl(self._tc)

        if evtHandler:
            self._tc.PushEventHandler(evtHandler)
            # so that handler is popped on exit
            self._tc.Bind(wx.EVT_WINDOW_DESTROY, self.OnDestroy)    

    def OnDestroy(self, evt):
        """
        Ensure that event handler pushed during Create() is removed.
        """
        self._tc.PopEventHandler()

None of my customised editors raise the exception but all the standard editors do:

    wx.grid.GridCellBoolEditor
    wx.grid.GridCellChoiceEditor
    wx.grid.GridCellFloatEditor
    wx.grid.GridCellNumberEditor
    wx.grid.GridCellTextEditor

As these all come from wxWidgets their internals aren't accessible.

**Comment by david-hughes** [comment]
Further to the above, an assertion error is also being raised on exit from a modal dialog containing a grid with an active wx.grid.GridCellChoiceEditor.

```
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.IdleEvent'> returned a result with an error set
```
I missed this earlier because it isn't being caught by Wing IDE, I guess because it is all happening outside the Python ecosystem?

I'm fairly sure this wasn't happening in earlier versions of Phoenix and my faciliites to revert are limited but I've just checked on an old system awaiting the scrap yard and wx 3.0.3 dev2875 produces both the flatnotebook and dialog exit assertion errors while 3.0.3 dev 2763 (Python 3.4) only errors with the flat notebook and **not** on exit from a dialog - if that's any help.

**Comment by RobinD42** [comment]
Can you replicate this in a small runnable sample?

**Comment by david-hughes** [comment]
These examples contain only wx.grid.GridCellChoiceEditor but demonstrate the same error message that I get when I mix in my own editors derived from wx.grid.GridCellEditor. As I said, I can get those to work on their own by explicitly popping the event handler (OnDestroy) that was pushed when the instance was created although - as a separate issue -  I've been struggling for a few days to find a way of reliably setting grid cell attributes and their reference counts that doesn't crash Python when things go out of scope - attr.Clone() seems to work best.

In each example, use one or more of the cell editors then close the notebook page.
[GridEdit01.txt](https://github.com/wxWidgets/Phoenix/files/1527512/GridEdit01.txt) works with Phoenix (Python 3.6) but neither
[GridEdit02.txt](https://github.com/wxWidgets/Phoenix/files/1527523/GridEdit02.txt) nor 
[GridEdit03.txt](https://github.com/wxWidgets/Phoenix/files/1527530/GridEdit03.txt)
do. All 3 work with Classic and I can't see why they shouldn't under Phoenix.

**Comment by RobinD42** [comment]
I've finally dug into this today to try and understand what is going on and I think that the current Phoenix behavior may be correct.  Not that it is raising an exception where it may not be expected, but that the design of the internal refcounting that is ultimately causing the exception to be raised and how it interacts with the wxPython wrapper code is currently doing the right thing.

Basically the exception is being raised because the C++ destructor for `wxGridCellEditor`, where that event handler is popped, is never called.  It is never called because its reference count never drops to zero.  You'll notice from your print messages that the editor's refcount is 4, but there are only 3 attr objects that it is assigned to. (Cloning a `GridCelAttr` will `IncRef` the editor and renderer objects, if any.) Adding a `editor.DecRef` to your GridEdit02 example removes the extra refcount and then the exception isn't raised.

I think the confusion and awkwardness comes from a mismatch between what wx is doing here and how Python object ref-counting works.  I've tried in the past (and again today) to reconcile and automate the ref-counts better, but I think that led to inconsistencies and more confusion because not every case could be covered. (At least one of the tweaks is still present in Classic which is likely why your examples worked okay there.) Since the types produced by SIP are closer to the actual C++ than it was with SWIG, I wasn't able to do the same as what is left in Classic without breaking things badly, so I think it's going to need to stay the way it is.  And by leaving out the tweaks things are actually a little simpler in some ways.

Basically the ref-counted objects have a refcount of 1 when they are created. This makes the common case easy to use, where the ref-counted object is only used by one other object, so you can just create and assign and not worry about managing the ref-count. That is why your first example works without raising an exception. But as soon as you want to use it in a 2nd or more objects then you need to increment the refcount for each one it is assigned to. You did this in your first example where you incremented the refcount for the attribute objects for only the 2nd and subsequent uses with this code:

```
            if row > 0:
                attr.IncRef()
```

To generalize how to deal with the ref-counts you could follow these rules:

1. `IncRef` the object whenever you pass it to  methods like `SetAttr`, `SetEditor`, `SetRenderer`.

2. If you created the object before calling `SetWhatever` then call `DecRef` to release the "local reference" to the object.

3. If the object is only going to be assigned once then the single `IncRef` and `DecRef` effectively cancel each other out so you could just not use them if desired.

4. Once a ref-counted object has been assigned to something you usually don't need to worry about `DecRef`ing or managing it in other ways, but I expect there are some corner cases that may need more help.

So following those rules the important bits of your examples now look something like this:


```python
        editor = wx.grid.GridCellChoiceEditor(choices)
        g.SetColSize(1, 200)
        for row in range(3):
            g.SetCellValue(row, 1, choices[row//2])

        if WHICH == 1:  # GridEdit01: Single shared Attr object
            attr = wx.grid.GridCellAttr()
            attr.SetEditor(editor)
            editor.IncRef() # optional since it is only assigned once

            for row in range(3):
                g.SetAttr(row, 1, attr)
                attr.IncRef()

            # release local refs
            editor.DecRef()
            attr.DecRef()

        if WHICH == 2:  # GridEdit02: Cloned Attr objects sharing Editor
            attr = wx.grid.GridCellAttr()
            attr.SetEditor(editor)
            editor.IncRef() # NOT optional since there will be multiple assignments
                            # due to the Clones

            for row in range(3):
                attr2 = attr.Clone()
                g.SetAttr(row, 1, attr2)
                # We'll skip IncRef'ing attr2 since it is only assigned once

            editor.DecRef() # we're done with the local reference
            attr.DecRef()

        if WHICH == 3:  # GridEdit03: New Attr objects sharing an Editor
            for row in range(3):
                attr = wx.grid.GridCellAttr()
                attr.SetEditor(editor)
                editor.IncRef()

                g.SetAttr(row, 1, attr)
                # Skipping IncRef'ing attr since it is only assigned once

            editor.DecRef() # give up the local reference
```

**Comment by david-hughes** [comment]
Many thanks for the detailed explanation. I've worked through your suggested strategies and things are becoming clearer. My real-life application is rather more compliceated due to the grid cell attributes and editors being updated as items are added into the grid and it is refreshed - but I'm making progress!

**Comment by RobinD42** [comment]
This issue has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/bug-error-with-slight-change-to-gridhugetable-py/34529/2
