### ISSUE TITLE
HyperTreeList setBackgroundImage not working

### ISSUE THREAD

**Issue by cristi94** [wxWidgets/Phoenix#641]
**Operating system**: Windows 7
**wxPython version**: 4.0.0b2
**Stock or custom build**:
**Python version**: 3.5
**Stock or custom build**:

**Description of the problem**:
Hi. I need to set a background image on my hypertreelist. I downloaded the demo from the snap-shop builds and saw that setBackgroundImage function is used. My python interpreter doesn't seem to know it. When I run the demo app, and try changing the background image nothing happens.

 

```python
# Put code sample here
```

**Comment by RobinD42** [comment]
Not sure what you mean by "My python interpreter doesn't seem to know it." Maybe that your IDE doesn't see the name in the `HyperTreeList` class? That's because it is delegated to the embedded `TreeListMainWindow` via monkey-patching. See the use of the `create_delegator_for` function at the end of the module.

The issue with the background image is due to the wrong background style being set on the window, which will be fixed in a PR to be submitted shortly.
