### ISSUE TITLE
CubeColourDialog shows opposite state for "Show Alpha Control" checkbox

### ISSUE THREAD

**Issue by robmcmullen** [wxWidgets/Phoenix#694]
**Operating system**: any
**wxPython version**: git-head
**Stock or custom build**: custom
**Python version**: 2.7
**Stock or custom build**: stock

**Description of the problem**:

The checkbox control is initially selected, but checking it once to turn off the alpha slider does nothing, and checking it again puts a check in the control but the alpha slider disappears. Continuing to hit the checkbox control shows the slider in the opposite state.

**Comment by Metallicow** [comment]
When I was hacking a 'pick color from screen' option into the dialog, I recall I addressed this issue also. But since it was a while back when I was doing a bunch of work on Robins fork, it got closed and a bit forgotten about. Thanks. 

@robmcmullen If you got a extra bit of time to dig it out, the 'pick color from screen' functionality never got merged either. I'm not sure when I may be able to get time to get back to it.
