### ISSUE TITLE
wx.CheckBox doesn't raise events wx.EVT_LEFT_UP(DOWN)

### ISSUE THREAD

**Issue by eldarkg** [wxWidgets/Phoenix#71]
wx.EVT_CHECKBOX - OK.
wx.EVT_LEFT_UP(DOWN) - Fail.
But wx.lib.inspection.InspectionTool().Show() Dialog shows this events
![inspection](https://cloud.githubusercontent.com/assets/5782069/14767803/a7a0ac64-0a37-11e6-8bb7-da854a4a1054.png)

**Comment by swt2c** [comment]
This is working for me.  Can you show your code where this is failing?

**Comment by eldarkg** [comment]
@swt2c The small sketch program:
```py
#!/usr/bin/env python3

import wx


def evt_cb(event):
    print('evt check box')

def evt_down(event):
    print('evt down')

def evt_up(event):
    print('evt up')

app=wx.App(False)
frm=wx.Frame(None)
cb=wx.CheckBox(frm, label='test')
frm.Bind(wx.EVT_CHECKBOX, evt_cb, cb) 
frm.Bind(wx.EVT_LEFT_DOWN, evt_down, cb) 
frm.Bind(wx.EVT_LEFT_UP, evt_up, cb) 
frm.Show()

import wx.lib.inspection
wx.lib.inspection.InspectionTool().Show()

app.MainLoop()
```
This is program prints the message 'evt check box' only

**Comment by swt2c** [comment]
Try instead:
````
cb.Bind(wx.EVT_LEFT_DOWN, evt_down)
cb.Bind(wx.EVT_LEFT_UP, evt_up)
```

**Comment by swt2c** [comment]
And don't forget `event.Skip()` in your callbacks.

**Comment by eldarkg** [comment]
@swt2c Thank you. This is work. Why the my variant didn't work?

**Comment by RobinD42** [comment]
Native widgets don't always play nice with the low-level events.  But I think your case is simpler than that. The native checkbox is handling the mouse events in order to do its native behavior of changing the state of the box, and since it has done its job it is assuming that no one else will need it after that so it marks the event as done.  The system sees that and doesn't bother passing the event up to the parent (the frame in your case.)  So where you do the event handler binding can make a difference.  

http://wiki.wxpython.org/self.Bind_vs._self.button.Bind
