### ISSUE TITLE
wx.SystemSettings.GetMetric(wx.SYS_FRAMESIZE_X) return value depend on python version

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#758]
**Operating system**: win 10
**wxPython version**: 4.0.1
**Stock or custom build**: stock
**Python version**: 3.5, 2.7
**Stock or custom build**: stock

**Description of the problem**:
on my win 10 machine with default theme, wx.SystemSettings.GetMetric(wx.SYS_FRAMESIZE_X) returns:
- 8 with wxpython 4.0.1, python 2.7
- 8 with wxpython classic , python 2.7
- 4 with wxpython 4.01., python 3.5
I would expect the same value in all the cases

**Comment by RobinD42** [comment]
On Windows that API is simply calling the Win32 API `GetSystemMetrics(SM_CXSIZEFRAME)` and returning the value.

I wouldn't think that this would have that kind of effect, but the major difference between the two builds besides the version of Python is the compiler (Python 2.7 requires VC 9 and Python 3.5+ requires VC 14) and that probably also means different versions of the Platform SDK libs. I suppose it's possible that the different return values are due to different implementations of `GetSystemMetrics` or something internal that it is based on. If so I don't think there's anything that we can fix.

**Comment by infinity77** [comment]
@swt2c : Python 2.7 is gone. Whatever the issue was, I’m not sure it’s actually an issue anymore
