### ISSUE TITLE
'AutoBufferedPaintDC' object has no attribute 'SelectObject'

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#766]
**Operating system**: Windows 10
**wxPython version**: 4.0.1
**Stock or custom build**: stock
**Python version**: 3.6
**Stock or custom build**: stock

**Description of the problem**:

`'AutoBufferedPaintDC' object has no attribute 'SelectObject'`

I have the following function (sorry, I don't have a small example yet, but can get one if needed):

```    
    def __init__(self, parent, pos, bitmap):
        ...
        self.Bind(wx.EVT_PAINT, self.OnWindowPaint)
        ...

    def OnWindowPaint(self, event):
        rect = self.GetRect()
        canvas = wx.Bitmap(rect.width, rect.height)
        mdc = wx.AutoBufferedPaintDC(self)
        mdc.SelectObject(canvas)
        mdc.DrawBitmap(self.bitmap, 0, 0)
        mdc.SetPen(wx.Pen("#000000", width=1))
        mdc.SetBrush(wx.TRANSPARENT_BRUSH)
        mdc.DrawRectangle(0, 0, rect.width, rect.height)
```

This used to work in Classic, but now breaks with the aforementioned error. Using `wx.BufferedPaintDC` works fine.

**Comment by mesalu** [comment]
Looks like this stems from a tweak done in etg.

As the docs say, some platforms already do the double buffering, and so `AutoBufferPaintDC`'s parent classes depend on which platform wxWidget's was derived from. Which causes some issues in the way the wrappers are made.

In essence, in order to fix compiler breaks, Phoenix pretends that it derives directly from `wx.DC`, instead of the intermediate classes, effectively losing `SelectObject` in the generated Python Bindings.

I'll tweak it back in when I get a chance. :)

**Comment by mesalu** [comment]
Relevant conversation is being carried out on pyfa's corresponding issue. Closing here.
