### ISSUE TITLE
wx.GLCanvas attribList parameter - zero terminator?

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#770]
This is wxGLCanvas' constructor:
```
wxGLCanvas (wxWindow *parent, wxWindowID id=wxID_ANY, const int *attribList=NULL,
    const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0,
    const wxString &name="GLCanvas", const wxPalette &palette=wxNullPalette)
```
The attribList parameter is a zero-terminated array of ints.
In Classic, the attribList parameter accepted a Python list without the zero terminator.
In Phoenix, it seems that the zero-terminator is now required.  Was this intentional?  On one hand, it matches the C++ API closer, but on the other hand, it seems less Pythonic.

**Comment by mesalu** [comment]
Hmm, my guess is that it was an unintended side effect. 
Since the intended input python-side is a deterministic iterable of integers, having a 0 terminator seems... redundant to me. I wonder if we could tweak in a check py-side before the cpp invocation occurs, that reads something like:

```Python
if attribList:
    if not attribList[len(attribList) - 1] is 0: # don't assume recieved iterable suports reverse indexing.
       attribList.append(0)    # assumes the received iterable supports `append`

# Carry on with SIP CPP invocation of the constructor
#   Which will convert attribList to a wxArrayInt, and then to const int*
```

That's not something I've looked into doing with `etg` though. 

@RobinD42, is something like this possible with SIP / ETG?

**Comment by mesalu** [comment]
Well, there we go. :)
