### ISSUE TITLE
Transparent background on Windows 10 fake

### ISSUE THREAD

**Issue by kobzar** [wxWidgets/Phoenix#793]
Help. 
I cant understand what i'm doing wrong.
I try to use image as background in my app. So, i have got simple example from web and run my script on different OS. 
On Linux and MacOS al working fine. 
But when i run it on Windows 10 my staticText background look like tkinter label - with grey border. 
For example the code:

https://python-scripts.com/wxpython-how-to-put-a-background-image-on-a-panel

i just add one string like this

self.lbl_UP = wx.StaticText(self, label="Some Test", pos=(100, 10))

On windows it's look bad:
<img width="221" alt="screen shot 2018-03-19 at 9 50 57 pm" src="https://user-images.githubusercontent.com/1912842/37618672-aa9522e6-2bbf-11e8-9fc3-22109f2b6f3c.png">
But must be without background. %(

**Comment by RobinD42** [comment]
This is due to differences in the native widgets on each platform. In the wxGTK port the native widget isn't a real widget, but just daws itself directly on the parent window. On the Mac it's more complex than that, but the net result is the same.

On Windows it is a real widget with its own window handle, foreground and background colors, ability to catch events, and so on. Probably the easiest fix for this is to just set the static text widget's background to be the same as the parent window's background (and resetting it if the parent's background color ever gets changed.) Another option would be to not use the static text widget at all and instead catch the parent's EVT_PAINT event and "draw" the text yourself.
