### ISSUE TITLE
Some context-menu items in PyShell.py demo do not work on Mac

### ISSUE THREAD

**Issue by tianzhuqiao** [wxWidgets/Phoenix#833]
On Mac, 
* run PyShell.py demo;
* some context-menu items (e.g., cut, copy, paste, clear, select all) do not work.

It looks like it is because the context-menu uses "system ID" (e.g., wx.ID_COPY) for these items (e.g., /py/shell.py). The problem goes away after creating new id for these menu items.

**Comment by RobinD42** [comment]
I still need to verify this but I think that this issue is due to how wxMac needs to do special processing for the standard clipboard and similar commands, and that they actually need to be routed through the Edit menu on the menubar for things to work correctly and to properly integrate with the system. When there is no Edit menu on the menubar then the events don't get routed properly and are lost.

Since the stock IDs will work properly when there is a proper Edit menu on the frame, then I'd rather not just change away from the stock IDs as your PR does. A better alternative would be to add a flag that would optionally use other IDs. Or perhaps you could just add a stock Edit menu to the demo's menubar when running on the Mac.

**Comment by tianzhuqiao** [comment]
I think you are right: if the same ids are added to the menu bar, it works fine. 

As shown in the link https://wiki.wxpython.org/SpecialIDs, using the stock id can help to “automatically specify the correct text (localized if available) for the item”. That’s nice.  But I am afraid it will be annoying to require always adding proper item to menu bar too. Is there any plan to “fix” the event routing issue in this case? If yes, then maybe just wait...

**Comment by RobinD42** [comment]
Not that I know of. IIRC, it is something imposed by the native API/Framework.
