### ISSUE TITLE
Custom panel reused in frame showing unusual

### ISSUE THREAD

**Issue by Applex007** [wxWidgets/Phoenix#868]
**Operating system**: win10
**wxPython version**: 4.0.1
**Stock or custom build**: 
**Python version**: python2.7.14
**Stock or custom build**:

**Description of the problem**:
 I want to customing a component based wxPanel and reusing it in a wxFrame. The showing of the second object was unusual, I couldn't find any error of my codes ,there is must something I don't know, someone help, thank you very much!

**demo codes as below**

```python
import wx

class ListPl(wx.Panel):
    def __init__(self, parent, size=(200, 200), pos=(0, 0), index=-1):
        wx.Panel.__init__(self, parent=parent, pos=pos, size=(100, 100))
        self.t1 = wx.StaticText(self, label="Test1")
        self.t2 = wx.StaticText(self, label="Test2")
        self.t3 = wx.StaticText(self, label="Test3")
        self.t1.SetBackgroundColour("RED")
        self.t2.SetBackgroundColour("YELLOW")
        self.t3.SetBackgroundColour("BLUE")

        self.vbox = wx.BoxSizer(wx.VERTICAL)
        self.vbox.Add(self.t1, proportion=0, flag=wx.ALL)
        self.vbox.Add(self.t2, proportion=0, flag=wx.ALL)
        self.vbox.Add(self.t3, proportion=0, flag=wx.ALL)
        self.SetSizer(self.vbox)
        self.SetBackgroundColour((size[0], size[1], 120+index*100))

import wx
from ListPl import ListPl


class TestFrame(wx.Frame):
    def __init__(self, parent, size=(960, 639)):
        wx.Frame.__init__(self, parent, title="test", size=size)
        self.lp = ListPl(self, size=(100, 100), index=1)
        self.lp2 = ListPl(self, size=(100, 100), index=2)
        print(self.lp.GetSize(), self.lp2.GetSize())
        rs = wx.BoxSizer(wx.VERTICAL)
        rs.Add(self.lp, flag=wx.ALL)
        rs.Add(self.lp2, flag=wx.ALL)
        self.SetSizer(rs)


if __name__ == "__main__":
    app = wx.App()
    TestFrame(None).Show()
    app.MainLoop()
```

![test](https://user-images.githubusercontent.com/22925077/40760349-fc1e1e1e-64c8-11e8-981c-ae5c2f1662d5.PNG)

**Comment by RobinD42** [comment]
Since you are creating the panels and frame with fixed sizes then there may not be any `EVT_SIZE` events sent to them after the widgets have been created and placed into sizers. It is inside the default `EVT_SIZE` event handlers where the sizers are asked to do their layout, so if there is no initial event then the initial layout will not happen and widgets will appear where they may not be expected to be. 

You can work around this lack of size event and layout by explicitly initiating one or the other by calling the frame's `SendSizeEvent` or `Layout` methods from `TestFrame.__init__`

**Comment by Applex007** [comment]
I'll  try it, thank you very much!
