### ISSUE TITLE
video help course

### ISSUE THREAD

**Issue by Moriand** [wxWidgets/Phoenix#900]
Hello, how are you, this message does not fit the theme, but the new ones are starting. Could you please create a complete and detailed course on how to use wxpython ?, I would be delighted if you will be on udemy or any other platform.

**Comment by DietmarSchwertberger** [comment]
I doubt that a video course would help a lot.

IMHO the easiest start is to download wxGlade and follow it's documentation. The new documentation was written with people in mind who have never used wx before. This should get you started to create your frames and handle the most important events. If you have problems to follow the documentation, please give me a note such that I can improve it.

Important: use at least wxGlade 0.8. If you know how to use git, you may prefer to use the version from the repository. This one has an improved user interface (one window instead of three).

**Comment by Metallicow** [comment]
When I started learning Python, I spent about 3-4 hours writing my first application. After that I almost immediately then installed wxPython and used sample apps from the wxPython Demo and googled most infos on the mailing lists and other sites that provide tutorials. The new [Phoenix docs](https://wxpython.org/Phoenix/docs/html/) are way better than the old docs, so you shouldn't have too much trouble. And the folks on the [mailing list](https://groups.google.com/forum/#!forum/wxpython-users) are always helpful. As far as wxGlade, I cannot comment as it wasn't part of my initial learning experience, but it is worth a shot since one of the community members recommends it.

**Comment by HelioGuilherme66** [comment]
@Moriand I agree what others said, just want to add that we have a [gallery](https://wxpython.org/pages/screenshots/) of applications to get examples of wxPython.
If you want to learn and at the same time help in a project, please see my [fork](https://github.com/HelioGuilherme66/RIDE) of RIDE. Help is welcome.

**Comment by Moriand** [comment]
Thank you very much for your answers, if I need your help, I will gladly let you know.
@DietmarSchwertberger         thank you
@Metallicow                           thank you
@HelioGuilherme66                thank you
