### ISSUE TITLE
GetMondrianData() returns bytes, not characters/strings

### ISSUE THREAD

**Issue by sinkva** [wxWidgets/Phoenix#959]
Operating system: MacOS 10.13.5 
wxPython version: 4.0.3 (Stock)
Python version: 3.7.0 (Stock)

Running thumbnailctrl.py gives:
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wx/lib/agw/thumbnailctrl.py", line 204, in GetMondrianImage
    stream = six.StringIO(GetMondrianData())
TypeError: initial_value must be str or None, not bytes

The description of GetMondrianData() says:
Returns a default image placeholder as a decompressed stream of characters.

But GetMondrianData() at
https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/agw/thumbnailctrl.py
def GetMondrianData():
    """ Returns a default image placeholder as a decompressed stream of characters. """
    return \
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00 \x00\x00\x00 \x08\x06\x00\
\x00\x00szz\xf4\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00qID\
ATX\x85\xed\xd6;\n\x800\x10E\xd1{\xc5\x8d\xb9r\x97\x16\x0b\xad$\x8a\x82:\x16\
o\xda\x84pB2\x1f\x81Fa\x8c\x9c\x08\x04Z{\xcf\xa72\xbcv\xfa\xc5\x08 \x80r\x80\
\xfc\xa2\x0e\x1c\xe4\xba\xfaX\x1d\xd0\xde]S\x07\x02\xd8>\xe1wa-`\x9fQ\xe9\
\x86\x01\x04\x10\x00\\(Dk\x1b-\x04\xdc\x1d\x07\x14\x98;\x0bS\x7f\x7f\xf9\x13\
\x04\x10@\xf9X\xbe\x00\xc9 \x14K\xc1<={\x00\x00\x00\x00IEND\xaeB`\x82'

Which is a byte-stream.

**Comment by mesalu** [comment]
Images aren't pure ascii/utf-8 characters, but rather binary data. As such, you're dealing with bytes that don't have may not have any relation to the typical character encoding schemas like ascii/utf-8. 
In python3 (more so than python2) data like this is preferred to be handled as byte-strings, rather than character strings.)
If anything, I'd say there's a defect in the docstring for hinting at string-usability. I recommend using `six.BytesIO` rather than `six.StringIO`

**Comment by RobinD42** [comment]
`GetMondrianImage` needs to be changed to use `BytesIO`.

**Comment by mesalu** [comment]
Oh, my bad. I though `StrinIO` was coming from submitter's code. Ooops, sorry all.

I'll create a PR for this shortly.
