### ISSUE TITLE
Scalar multiplication and division for wx.Point and friends

### ISSUE THREAD

**Issue by RobinD42** [wxWidgets/Phoenix#971]
**Operating system**: any
**wxPython version & source**: any
**Python version & source**: any

**Description of the problem**:

Multiplying a `wx.Point` by a double ends up truncating the floating point value before passing it to the C++ operator. This is likely just due to not including a wrapper for the `double` version of the operator.

Add the missing `double` operators for `wx.Point`, and others, and corresponding unit tests.  I think sip will be able to handle overloads between int/double, but that will need to be verified.

**Comment by mesalu** [comment]
There's an overloading issue in SIP if we add the extra overload to WIG code. Options are to take a hit by coercing all scalar arithmetic to double precision (overal minor hit, but could potentially stack up in computationally complex drawing?)
or try to solve the issue at a far lower level.

@RobinD42, thoughts?

**Comment by RobinD42** [comment]
I think it would be okay to just provide the `double` version of those operator wrappers.

**Comment by itsayellow** [comment]
In particular I noticed that wx.RealPoint doesn't allow multiplication by a floating point number, which seemed particularly non-intuitive, since the actual point is already a floating point value.

Would wx.RealPoint count as a "friend" of wx.Point that could get this ability to multiply by a floating point number?  That would be awesome.

**Comment by mesalu** [comment]
@itsayellow, yes, it is one of the classes affected.
