### ISSUE TITLE
BoxSizer do not follow proportion value

### ISSUE THREAD

**Issue by NeiroNx** [wxWidgets/Phoenix#977]
**Operating system**: win32
**wxPython version & source**: PyPi = wxPython 4.0.3 (wxMSW, unicode, unicode-wchar, wx-assertions-on, phoenix, wxWidgets 3.0.5, autoidman, build-type: release) Running on Python 3.7.0
**Python version & source**: stock 3.7

**Description of the problem**:
When BoxSizer have item with very big size (Grid with many rows) other items resized to 0 and do not visible. When resizing to minnimal size - items resized in some order. Firs resized item with proportion 20 and it size sets to 0, second resized item with proportion 30 and it size sets to 0 finaly resized item with proportion 50. But in previos versions all items resized and it size sets with it proportion and can be 0 only if size of parent is 0.

**Comment by NeiroNx** [comment]
![test](https://user-images.githubusercontent.com/4705299/44723196-d5117780-aabe-11e8-856c-5dad323b64be.png)
```python
import wx

labels = "one two three four".split()
class VBoxSizerMultiProportionalFrame(wx.Frame):
    title = "Proportional BoxSizer"
    def __init__(self):
        wx.Frame.__init__(self, None, -1, self.title)
        sizer = self.CreateSizerAndWindows()
        self.SetSizer(sizer)
        self.Fit()
    
    def CreateSizerAndWindows(self):
        sizer = wx.BoxSizer(wx.VERTICAL)
        for label in labels:
            bw = wx.Button(self, wx.ID_ANY,label, size=(200,30))
            sizer.Add(bw, flag=wx.EXPAND)

        # Add an item that takes one share of the free space
        bw = wx.Button(self, wx.ID_ANY,"gets 1/3 of the free space", 
                size=(200,30))
        sizer.Add(bw, 1, flag=wx.EXPAND)

        # Add an item that takes 2 shares of the free space
        bw = wx.Button(self, wx.ID_ANY,"gets 2/3 of the free space", 
                size=(200,30))
        sizer.Add(bw, 2, flag=wx.EXPAND)
        return sizer

app = wx.PySimpleApp()
VBoxSizerMultiProportionalFrame().Show()
app.MainLoop()
```

**Comment by RobinD42** [comment]
This is due to changes that were made to sizers sometime in the 2.9 release series. I don't remember all the details at the moment but I think it had to do with ensuring that items with a minsize get at least that much space. Or maybe it was bestsize (and if there is a minsize then it takes priority over bestsize like normal.)

In your 2nd example the buttons are being created with a size, which automatically sets their minsize property. So the "1/3" button will get its 30 pixels height before the "2/3" button gets its 2/3 of the free space.

There was some some controversy at the time the changes were made, but IIRC most people eventually agreed that it was better the new way.
